# Copyright (c) 2025-2026 K.N.Narin. Non-commercial use only. See LICENSE.
"""Batch 2: broad coverage toward a full 'job dictionary'. Append-only, deduped by
id and title. ASCII-only text. Run:  python scripts/add_jobs_batch2.py
"""
import json, os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PATH = os.path.join(HERE, "backend", "data", "careers.json")


def C(cid, title, category, collar, smin, smax, note, desc, skills, paths, quals, tags, work, growth):
    return {
        "id": cid, "title": title, "category": category, "region": "IN",
        "description": desc,
        "salary_range": {"min": smin, "max": smax, "currency": "INR/month", "note": note},
        "growth_outlook": growth,
        "work_style": work,
        "required_skills": [{"skill": s, "level": l} for s, l in skills],
        "entry_paths": paths, "qualifications": quals, "tags": tags, "collar": collar,
    }


def S(*pairs):  # skills helper: S(("Python","critical"), ...)
    return list(pairs)


NEW = [
    # ===================== Healthcare =====================
    C("general_physician_in", "General Physician (MBBS Doctor)", "Healthcare", "white", 40000, 250000,
      "Junior resident to established practitioner/consultant",
      "Diagnose and treat common illnesses, manage patients, and refer to specialists. The frontline of clinical medicine in hospitals, clinics and private practice.",
      S(("Clinical Diagnosis","critical"),("Patient Management","critical"),("Pharmacology","critical"),
        ("Medical Ethics","important"),("Emergency Care","important"),("Communication & Empathy","important")),
      ["Complete MBBS + internship","Register with the Medical Council (NMC/state)","Practise or pursue PG (MD/MS)"],
      ["MBBS degree","NMC/State Medical Council registration"],
      ["doctor","medicine","healthcare","clinical"], ["Hospital/Clinic","Knowledge work","High-responsibility"], "Strong - persistent doctor demand"),
    C("surgeon_in", "Surgeon (General / Specialist)", "Healthcare", "white", 80000, 800000,
      "Resident to senior consultant surgeon",
      "Perform surgical procedures to treat injury, disease and deformity, from general surgery to specialised fields. High-skill, high-responsibility medical work.",
      S(("Surgical Technique","critical"),("Anatomy","critical"),("Patient Assessment","critical"),
        ("Sterile/OT Protocols","important"),("Post-op Care","important"),("Decision-making Under Pressure","important")),
      ["MBBS then MS/MCh in a surgical specialty","Surgical residency and supervised practice","Hospital consultant or private practice"],
      ["MBBS + MS/MCh (surgical specialty)","NMC registration"],
      ["surgeon","surgery","medicine","specialist"], ["Hospital","High-responsibility","Knowledge work"], "Strong - specialist demand"),
    C("pediatrician_in", "Pediatrician", "Healthcare", "white", 60000, 400000,
      "Resident to senior child-health consultant",
      "Care for the health of infants, children and adolescents - growth, vaccination, and treatment of childhood illnesses.",
      S(("Child Health & Development","critical"),("Clinical Diagnosis","critical"),("Vaccination/Immunisation","important"),
        ("Parent Communication","important"),("Emergency Pediatrics","important")),
      ["MBBS then MD/DNB Paediatrics","Residency and registration","Hospital or private clinic"],
      ["MBBS + MD/DNB (Paediatrics)","NMC registration"],
      ["pediatrician","child-health","doctor","medicine"], ["Hospital/Clinic","Knowledge work"], "Strong"),
    C("dentist_in", "Dentist (BDS)", "Healthcare", "white", 30000, 250000,
      "New graduate to established dental practice owner",
      "Diagnose and treat teeth and gum conditions - fillings, extractions, root canals, cosmetic and preventive dentistry.",
      S(("Dental Procedures","critical"),("Oral Diagnosis","critical"),("Patient Care","important"),
        ("Dental Equipment Handling","important"),("Practice Management","helpful")),
      ["Complete BDS + internship","Register with Dental Council","Clinic job, then own practice or MDS specialisation"],
      ["BDS degree","Dental Council registration"],
      ["dentist","dental","healthcare"], ["Clinic","Hands-on","Self-employed option"], "Good"),
    C("pharmacist_in", "Pharmacist", "Healthcare", "white", 18000, 80000,
      "Retail/hospital pharmacist to pharmacy owner",
      "Dispense medicines, advise on usage and interactions, and manage pharmacy inventory in retail, hospital or industry settings.",
      S(("Pharmacology","critical"),("Dispensing & Prescription Reading","critical"),("Drug Interactions","important"),
        ("Inventory Management","important"),("Patient Counselling","helpful")),
      ["D.Pharm or B.Pharm","Register with State Pharmacy Council","Work in retail/hospital/industry or open a pharmacy"],
      ["D.Pharm / B.Pharm","State Pharmacy Council registration"],
      ["pharmacist","pharmacy","healthcare","medicine"], ["Retail/Hospital","Knowledge work"], "Good"),
    C("physiotherapist_in", "Physiotherapist", "Healthcare", "white", 20000, 120000,
      "Clinic therapist to own physiotherapy practice",
      "Restore movement and function for patients with injury, illness or disability through exercise, manual therapy and rehabilitation.",
      S(("Physiotherapy Techniques","critical"),("Anatomy & Kinesiology","critical"),("Rehabilitation Planning","important"),
        ("Patient Motivation","important"),("Electrotherapy/Modalities","helpful")),
      ["BPT degree + internship","Register with state council","Hospital/clinic or own practice; sports/ortho specialisation"],
      ["BPT (Bachelor of Physiotherapy)","State council registration"],
      ["physiotherapy","rehab","healthcare","wellness"], ["Clinic/Hospital","Hands-on"], "Growing - rehab & sports demand"),
    C("nurse_practitioner_in", "Staff Nurse / Nursing Officer", "Healthcare", "white", 18000, 90000,
      "Staff nurse to nursing superintendent",
      "Provide patient care, administer medication, assist procedures and monitor recovery in hospitals and clinics.",
      S(("Patient Care","critical"),("Medication Administration","critical"),("Vitals & Monitoring","critical"),
        ("Infection Control","important"),("Emergency Response","important"),("Empathy","important")),
      ["GNM diploma or B.Sc Nursing","Register with Nursing Council","Hospital roles; specialise (ICU/OT/cardiac)"],
      ["GNM / B.Sc Nursing","State Nursing Council registration"],
      ["nurse","nursing","healthcare","patient-care"], ["Hospital","Shift work","Hands-on"], "Strong - global nurse shortage"),
    C("lab_technician_in", "Medical Lab Technician", "Healthcare", "white", 15000, 60000,
      "Lab technician to lab supervisor",
      "Collect samples and run diagnostic tests (blood, urine, pathology) that doctors rely on for diagnosis.",
      S(("Sample Collection & Handling","critical"),("Lab Test Procedures","critical"),("Lab Equipment Operation","important"),
        ("Quality Control","important"),("Biosafety","important")),
      ["DMLT/B.Sc MLT","Lab internship","Hospital/diagnostic-lab roles"],
      ["DMLT / B.Sc in Medical Lab Technology"],
      ["lab-technician","pathology","healthcare","diagnostics"], ["Lab","Hands-on"], "Good - diagnostics growth"),
    C("radiology_technician_in", "Radiology / X-Ray Technician", "Healthcare", "white", 18000, 70000,
      "Technician to radiology supervisor",
      "Operate X-ray, CT and MRI machines to capture diagnostic images while ensuring patient and radiation safety.",
      S(("Imaging Equipment Operation","critical"),("Radiation Safety","critical"),("Patient Positioning","important"),
        ("Image Quality Assessment","important")),
      ["B.Sc/Diploma in Radiology/Imaging Technology","Hospital internship","Diagnostic centre/hospital roles"],
      ["Diploma/B.Sc in Radiology / Medical Imaging Technology"],
      ["radiology","imaging","healthcare","x-ray"], ["Hospital/Diagnostic centre","Technical"], "Good"),
    C("paramedic_emt_in", "Paramedic / Emergency Medical Technician", "Healthcare", "white", 15000, 60000,
      "EMT to senior paramedic / ambulance supervisor",
      "Provide pre-hospital emergency care and transport - first response, life support and stabilisation en route to hospital.",
      S(("Emergency First Response","critical"),("Basic/Advanced Life Support","critical"),("Patient Stabilisation","important"),
        ("Ambulance Operations","important"),("Calm Under Pressure","important")),
      ["EMT/paramedic certification course","Ambulance/hospital emergency roles"],
      ["EMT / Paramedic certification (e.g. from a recognised institute)"],
      ["paramedic","emt","emergency","healthcare"], ["Field/Ambulance","On-call","High-pressure"], "Growing - emergency services expansion"),
    C("medical_coder_in", "Medical Coder / Billing Specialist", "Healthcare", "white", 18000, 70000,
      "Coder to coding team lead/auditor",
      "Translate diagnoses and procedures into standardized codes (ICD/CPT) for insurance and records. A large remote-friendly healthcare-BPO field in India.",
      S(("Medical Coding (ICD-10/CPT)","critical"),("Medical Terminology","critical"),("Anatomy basics","important"),
        ("Insurance/Claims Process","important"),("Accuracy & Compliance","important")),
      ["Life-science/nursing/pharma background helps","Medical coding certification (CPC/CCS)","Healthcare BPO roles (often remote)"],
      ["Coding certification (CPC/CCS) preferred","Any science/health graduate"],
      ["medical-coding","healthcare","bpo","remote"], ["Office / Remote","Knowledge work"], "Strong - healthcare BPO growth"),
    C("optometrist_in", "Optometrist", "Healthcare", "white", 18000, 90000,
      "Optometrist to optical store owner",
      "Test vision, prescribe spectacles/contact lenses and screen for eye conditions, often alongside ophthalmologists or in optical retail.",
      S(("Vision Testing & Refraction","critical"),("Eye Anatomy","important"),("Lens/Contact Fitting","important"),
        ("Patient Counselling","important"),("Optical Retail","helpful")),
      ["B.Optom or diploma in optometry","Clinic/optical-retail roles","Own optical store"],
      ["B.Optom / Diploma in Optometry"],
      ["optometry","eye-care","healthcare"], ["Clinic/Retail","Hands-on"], "Good"),
    C("veterinarian_in", "Veterinarian", "Veterinary & Animal Care", "white", 25000, 200000,
      "Vet to own clinic / specialist",
      "Diagnose and treat animals - pets, livestock and wildlife - including surgery, vaccination and preventive care.",
      S(("Animal Diagnosis & Treatment","critical"),("Veterinary Surgery","important"),("Animal Handling","critical"),
        ("Pharmacology (vet)","important"),("Client Communication","helpful")),
      ["BVSc & AH degree","Register with Veterinary Council","Clinic/livestock/govt roles or own practice"],
      ["BVSc & AH degree","Veterinary Council registration"],
      ["veterinarian","animal-care","healthcare"], ["Clinic/Field","Hands-on"], "Growing - pet care boom"),

    # ===================== IT / Tech (gaps) =====================
    C("qa_engineer_in", "QA / Test Engineer", "Technology", "white", 30000, 180000,
      "Junior QA to QA lead/SDET",
      "Ensure software quality through manual and automated testing - writing test cases, finding bugs, and building test automation.",
      S(("Test Case Design","critical"),("Manual Testing","critical"),("Test Automation (Selenium/Cypress)","important"),
        ("Bug Tracking (JIRA)","important"),("API Testing","important"),("Basic Programming","helpful")),
      ["CS/IT degree or self-study","Learn testing + an automation tool","QA roles, grow to SDET/lead"],
      ["Any degree; testing certifications (ISTQB) optional"],
      ["qa","testing","software","automation"], ["Office / Remote","Team-based"], "Strong"),
    C("sre_in", "Site Reliability Engineer (SRE)", "Technology", "white", 80000, 400000,
      "SRE to senior/staff SRE",
      "Keep large systems reliable and scalable - monitoring, incident response, automation and performance, blending software and operations.",
      S(("Linux & Networking","critical"),("Cloud (AWS/GCP/Azure)","critical"),("Monitoring & Observability","critical"),
        ("Scripting (Python/Go)","important"),("Incident Management","important"),("Infrastructure as Code","important")),
      ["Strong software + systems background","Cloud and observability skills","Move from SWE/DevOps into SRE"],
      ["CS/IT degree or equivalent experience","Cloud certifications (optional)"],
      ["sre","reliability","devops","cloud"], ["Office / Remote","On-call","High-responsibility"], "Strong"),
    C("dba_in", "Database Administrator (DBA)", "Technology", "white", 40000, 220000,
      "DBA to senior/lead DBA",
      "Design, secure, tune and maintain databases - ensuring data availability, performance and backups for applications.",
      S(("SQL & Query Tuning","critical"),("Database Administration (Oracle/PostgreSQL/MySQL)","critical"),
        ("Backup & Recovery","important"),("Security & Access Control","important"),("Performance Monitoring","important")),
      ["CS/IT background","Master a major DBMS","DBA roles in enterprises/cloud"],
      ["Any IT degree; DB vendor certifications optional"],
      ["dba","database","sql","data"], ["Office / Remote","Knowledge work"], "Stable"),
    C("network_engineer_in", "Network Engineer", "Technology", "white", 30000, 180000,
      "Network engineer to network architect",
      "Design, configure and maintain computer networks - routers, switches, firewalls, VPNs - for reliable, secure connectivity.",
      S(("Networking (TCP/IP, routing, switching)","critical"),("Network Security/Firewalls","important"),
        ("Cisco/Juniper Equipment","important"),("Troubleshooting","critical"),("Cloud Networking","helpful")),
      ["IT/ECE background","CCNA and hands-on labs","NOC/network roles, grow to architect"],
      ["Any IT/ECE degree","CCNA/CCNP certifications valued"],
      ["networking","infrastructure","it","cisco"], ["Office/Datacentre","Technical"], "Stable"),
    C("it_support_in", "IT Support / Help Desk Technician", "Technology", "white", 15000, 60000,
      "Support tech to IT support lead",
      "Provide first-line technical support - troubleshooting hardware, software, accounts and networks for users.",
      S(("Hardware & OS Troubleshooting","critical"),("Networking Basics","important"),("Ticketing Systems","important"),
        ("Customer Service","important"),("Remote Support Tools","helpful")),
      ["IT diploma/degree or self-study","Entry help-desk roles","Grow into sysadmin/network roles"],
      ["Any IT background; CompTIA A+ optional"],
      ["it-support","helpdesk","technician","it"], ["Office / Remote","Customer-facing"], "Stable"),
    C("sysadmin_in", "Systems Administrator", "Technology", "white", 30000, 160000,
      "Sysadmin to infrastructure lead",
      "Install, configure and maintain servers and IT infrastructure - keeping systems secure, updated and running.",
      S(("Linux/Windows Server Admin","critical"),("Scripting (Bash/PowerShell)","important"),("Virtualization","important"),
        ("Backup & Security","important"),("Networking","important")),
      ["IT background","Server admin skills","Sysadmin roles; move to DevOps/SRE"],
      ["Any IT degree; RHCSA/MCSA optional"],
      ["sysadmin","infrastructure","linux","it"], ["Office/Datacentre","Technical"], "Stable"),
    C("technical_writer_in", "Technical Writer", "Technology", "white", 25000, 150000,
      "Junior to senior/lead technical writer",
      "Create clear documentation - API docs, user guides, manuals - making complex products understandable.",
      S(("Technical Writing","critical"),("Understanding Tech/APIs","important"),("Docs Tools (Markdown/Git)","important"),
        ("Information Architecture","important"),("Editing","important")),
      ["Strong writing + tech interest","Build a docs portfolio","Software-company writing roles"],
      ["Any degree; writing/STEM background helps"],
      ["technical-writing","documentation","content","software"], ["Office / Remote","Knowledge work"], "Good"),
    C("game_designer_in", "Game Designer", "Gaming & Esports", "white", 30000, 200000,
      "Junior designer to lead game designer",
      "Design game mechanics, levels, systems and player experience - the creative blueprint behind games.",
      S(("Game Design & Mechanics","critical"),("Level Design","important"),("Prototyping (Unity/Unreal)","important"),
        ("Player Psychology","important"),("Storytelling","helpful")),
      ["Build small games / a portfolio","Game design course or self-study","Studio roles"],
      ["Any degree; game design portfolio is key"],
      ["game-design","gaming","creative","unity"], ["Studio / Remote","Creative"], "Growing - gaming industry"),
    C("pentester_in", "Penetration Tester / Ethical Hacker", "Technology", "white", 40000, 300000,
      "Junior pentester to security consultant",
      "Legally attack systems to find vulnerabilities before criminals do - web, network, cloud and app security testing.",
      S(("Ethical Hacking & Exploitation","critical"),("Networking & Web Security","critical"),("Scripting (Python)","important"),
        ("Security Tools (Burp/Metasploit)","important"),("Reporting","important")),
      ["Strong security fundamentals","Practise on labs (HTB/TryHackMe), get OSCP/CEH","Security firm/consultancy roles"],
      ["Any IT degree","OSCP/CEH certifications valued"],
      ["pentesting","ethical-hacking","cybersecurity","security"], ["Office / Remote","High-skill"], "Strong - security demand"),
    C("soc_analyst_in", "SOC Analyst (Security Operations)", "Technology", "white", 30000, 180000,
      "L1 analyst to SOC lead/threat hunter",
      "Monitor, detect and respond to security threats in real time using SIEM tools in a Security Operations Centre.",
      S(("Security Monitoring (SIEM)","critical"),("Incident Response","critical"),("Networking & Logs","important"),
        ("Threat Intelligence","important"),("Scripting","helpful")),
      ["Security fundamentals + SIEM training","SOC L1 roles, grow to threat hunting"],
      ["Any IT degree","Security certs (CompTIA Security+, etc.) valued"],
      ["soc","cybersecurity","monitoring","security"], ["Office / Remote","Shift work"], "Strong"),
    C("salesforce_dev_in", "Salesforce Developer / Admin", "Technology", "white", 40000, 250000,
      "Admin to senior Salesforce developer/architect",
      "Customize and build on the Salesforce CRM platform - automation, integrations and apps for businesses.",
      S(("Salesforce Admin & Config","critical"),("Apex/Lightning Development","important"),("Flows & Automation","important"),
        ("Integrations","important"),("CRM Process Knowledge","helpful")),
      ["Learn Salesforce via Trailhead","Get certified (Admin/Developer)","CRM consultancy/enterprise roles"],
      ["Any degree","Salesforce certifications (Admin/Platform Dev)"],
      ["salesforce","crm","software","cloud"], ["Office / Remote","Knowledge work"], "Strong"),
    C("sap_consultant_in", "SAP / ERP Consultant", "Technology", "white", 40000, 300000,
      "Consultant to senior/principal consultant",
      "Implement and customise SAP/ERP modules for enterprises - finance, supply chain, HR - bridging business and tech.",
      S(("SAP/ERP Module Expertise","critical"),("Business Process Mapping","critical"),("Configuration","important"),
        ("Stakeholder Communication","important"),("ABAP basics","helpful")),
      ["Domain or IT background","SAP module training/certification","Consultancy/enterprise implementation roles"],
      ["Any degree; SAP module certification valued"],
      ["sap","erp","consulting","enterprise"], ["Office / Client-site","Knowledge work"], "Strong"),

    # ===================== Skilled trades / construction =====================
    C("mason_in", "Mason / Bricklayer (Raj Mistri)", "Trades & Construction", "blue", 15000, 60000,
      "Helper to master mason/contractor",
      "Build walls, structures and finishes with brick, block, stone and concrete - core of every construction project.",
      S(("Bricklaying & Blockwork","critical"),("Plastering & Finishing","critical"),("Reading Basic Drawings","important"),
        ("Mixing & Curing","important"),("Site Safety","important")),
      ["Learn on-site as a helper under a master mason","ITI/skill-training (optional)","Become a contractor"],
      ["No formal degree - apprenticeship","ITI in masonry (optional)"],
      ["mason","construction","trades","skilled-labour"], ["Site","Physical","Self-employed option"], "Stable - construction demand"),
    C("building_painter_in", "Painter (Building / Decorative)", "Trades & Construction", "blue", 14000, 55000,
      "Helper to painting contractor",
      "Prepare surfaces and apply paints, textures and finishes to buildings - interior and exterior.",
      S(("Surface Prep & Painting","critical"),("Texture/Decorative Finishes","important"),("Colour Mixing","important"),
        ("Tools & Spray Equipment","important"),("Site Safety","important")),
      ["Learn on-site under experienced painters","Take painting jobs, build a crew","Become a contractor"],
      ["No formal degree - apprenticeship"],
      ["painter","construction","trades","finishing"], ["Site","Physical","Self-employed option"], "Stable"),
    C("surveyor_in", "Land Surveyor", "Architecture & Urban Planning", "white", 18000, 90000,
      "Survey assistant to licensed surveyor",
      "Measure and map land, boundaries and construction sites using instruments and software for building and legal purposes.",
      S(("Surveying (Total Station/GPS)","critical"),("CAD & Mapping Software","important"),("Measurement & Calculation","critical"),
        ("Field Data Collection","important"),("Drawing Interpretation","important")),
      ["Diploma in civil/surveying","Field assistant roles","Govt/private surveying, licensing"],
      ["Diploma/Degree in Civil Engineering or Surveying"],
      ["surveyor","construction","mapping","civil"], ["Field + Office","Technical"], "Good - infrastructure growth"),
    C("heavy_equipment_operator_in", "Heavy Equipment Operator", "Trades & Construction", "blue", 18000, 70000,
      "Operator to senior operator/supervisor",
      "Operate excavators, cranes, loaders, bulldozers and other heavy machinery on construction and infrastructure sites.",
      S(("Heavy Machinery Operation","critical"),("Site Safety","critical"),("Basic Machine Maintenance","important"),
        ("Load/Ground Awareness","important")),
      ["Equipment operator training/ITI","On-site experience","Construction/infra/mining roles"],
      ["ITI or operator training certification"],
      ["heavy-equipment","construction","operator","trades"], ["Site","Physical","Technical"], "Good - infrastructure push"),
    C("welder_pipe_in", "Welder / Fabricator", "Manufacturing & Production", "blue", 16000, 80000,
      "Welder to certified pipe/structural welder",
      "Join metal parts using welding techniques (arc, MIG, TIG) for construction, fabrication and industry. Certified welders are in global demand.",
      S(("Welding (Arc/MIG/TIG)","critical"),("Blueprint/Drawing Reading","important"),("Metal Cutting & Grinding","important"),
        ("Welding Safety","critical"),("Quality/Inspection awareness","helpful")),
      ["ITI in welding or trade training","Build experience and get welding certifications","Fabrication/construction/oil-and-gas roles"],
      ["ITI (Welder trade)","Welding certifications (e.g. for pipeline) valued"],
      ["welding","fabrication","trades","manufacturing"], ["Workshop/Site","Physical","Skilled"], "Strong - skilled-welder shortage"),
    C("solar_installer_in", "Solar Panel Installer / Technician", "Energy & Utilities", "blue", 16000, 70000,
      "Installer to solar project technician/entrepreneur",
      "Install, wire and maintain rooftop and ground solar PV systems - a fast-growing green-jobs field backed by India's solar mission.",
      S(("Solar PV Installation","critical"),("Electrical Wiring & Safety","critical"),("Panel & Inverter Setup","important"),
        ("Maintenance & Troubleshooting","important"),("Site Assessment","helpful")),
      ["ITI (electrician) + solar training (e.g. Suryamitra)","Installer roles with solar firms","Own solar installation service"],
      ["ITI electrical + Suryamitra/solar technician certification"],
      ["solar","green-jobs","renewable","technician"], ["Field/Rooftop","Physical","Technical"], "Growing fast - solar push"),
    C("lift_technician_in", "Lift / Elevator Technician", "Trades & Construction", "blue", 18000, 75000,
      "Technician to service supervisor",
      "Install, service and repair lifts and escalators in buildings - a specialised electromechanical trade with steady urban demand.",
      S(("Electromechanical Systems","critical"),("Lift Installation & Service","critical"),("Electrical Troubleshooting","important"),
        ("Safety Standards","critical")),
      ["ITI (electrical/mechanical)","OEM/installer training","Service contracts with lift companies"],
      ["ITI electrical/mechanical + manufacturer training"],
      ["lift","elevator","technician","trades"], ["Field/Building","Technical","Hands-on"], "Good - urban construction"),
    C("locksmith_in", "Locksmith", "Everyday Work & Trades", "blue", 12000, 50000,
      "Apprentice to own locksmith service",
      "Install, repair and open locks and security systems - keys, safes, automotive and digital locks.",
      S(("Lock Mechanisms & Repair","critical"),("Key Cutting","critical"),("Security Systems","important"),
        ("Customer Trust & Ethics","important")),
      ["Learn under an experienced locksmith","Build tools and clientele","Mobile or shop service"],
      ["No formal degree - apprenticeship"],
      ["locksmith","security","trades","self-employment"], ["Mobile/Shop","Hands-on","Self-employed"], "Stable"),
    C("pest_control_in", "Pest Control Technician", "Everyday Work & Trades", "blue", 14000, 60000,
      "Technician to pest-control business owner",
      "Inspect and treat homes and businesses for pests - insects, rodents, termites - using safe chemical and non-chemical methods.",
      S(("Pest Identification","critical"),("Safe Pesticide Handling","critical"),("Treatment Methods","important"),
        ("Customer Service","important"),("Safety & Compliance","important")),
      ["On-the-job training with a pest-control firm","Certification/licensing where required","Own a pest-control service"],
      ["No formal degree; pesticide-handling certification"],
      ["pest-control","services","trades","self-employment"], ["Field","Hands-on","Self-employed option"], "Stable"),

    # ===================== Hospitality / service =====================
    C("hotel_manager_in", "Hotel Manager", "Food & Hospitality", "white", 30000, 250000,
      "Trainee to general manager",
      "Run hotel operations - guest experience, staff, rooms, F&B and revenue - ensuring smooth, profitable service.",
      S(("Hospitality Operations","critical"),("Team & Staff Management","critical"),("Guest Relations","important"),
        ("Revenue/Cost Management","important"),("Problem-solving","important")),
      ["Hotel management degree/diploma","Work up from operations roles","Manage properties"],
      ["Degree/Diploma in Hotel Management (IHM, etc.)"],
      ["hotel","hospitality","management","service"], ["Hotel","Customer-facing","Leadership"], "Good - tourism growth"),
    C("chef_in", "Chef de Cuisine / Executive Chef", "Food & Hospitality", "no", 25000, 250000,
      "Commis to executive chef / restaurateur",
      "Lead a kitchen - menu creation, cooking, food quality and kitchen team - in restaurants, hotels or own ventures.",
      S(("Culinary Skills & Cuisine Knowledge","critical"),("Menu Planning","important"),("Kitchen Management","critical"),
        ("Food Safety & Hygiene","important"),("Cost Control","helpful")),
      ["Culinary diploma or kitchen apprenticeship","Work up the kitchen brigade","Head a kitchen or open a restaurant"],
      ["Culinary diploma or hands-on kitchen experience"],
      ["chef","culinary","food","hospitality"], ["Kitchen","Creative","Physical"], "Good - food & cloud-kitchen boom"),
    C("bartender_in", "Bartender / Mixologist", "Food & Hospitality", "pink", 15000, 90000,
      "Bartender to head bartender/bar manager",
      "Mix and serve drinks, craft cocktails and create great bar experiences in bars, hotels and events.",
      S(("Mixology & Cocktail Craft","critical"),("Customer Service","critical"),("Bar Operations & Inventory","important"),
        ("Speed & Showmanship","important")),
      ["Bartending course or on-the-job training","Bar roles, build a signature style","Bar manager / consultant"],
      ["Bartending/mixology course (optional)"],
      ["bartender","mixology","hospitality","service"], ["Bar/Events","Customer-facing","Evening shifts"], "Good"),
    C("event_planner_in", "Event Planner / Manager", "Media & Broadcasting", "no", 20000, 200000,
      "Coordinator to own event company",
      "Plan and execute events - weddings, corporate, concerts - handling logistics, vendors, budgets and on-day coordination.",
      S(("Event Planning & Logistics","critical"),("Vendor & Budget Management","critical"),("Client Relations","important"),
        ("Creativity & Theming","important"),("Crisis Management","important")),
      ["Event-management course or assist an event company","Build a portfolio and vendor network","Start your own events business"],
      ["Any degree; event management diploma helps"],
      ["events","wedding","management","self-employment"], ["On-site","High-energy","Self-employed option"], "Good - events economy"),
    C("travel_agent_in", "Travel Agent / Tour Operator", "Transport & Logistics", "no", 15000, 150000,
      "Agent to travel-agency owner",
      "Plan and book travel - flights, hotels, tours and packages - and craft itineraries for leisure and business travellers.",
      S(("Travel Planning & Booking","critical"),("Destination Knowledge","important"),("Customer Service","critical"),
        ("Vendor Negotiation","important"),("Marketing","helpful")),
      ["Travel & tourism course or agency experience","Build supplier tie-ups","Run an agency / niche tours"],
      ["Diploma in Travel & Tourism (optional)"],
      ["travel","tourism","booking","self-employment"], ["Office / Remote","Customer-facing"], "Good - travel recovery"),

    # ===================== Retail / sales / business =====================
    C("retail_manager_in", "Retail Store Manager", "Retail & Commerce", "white", 20000, 120000,
      "Supervisor to area/regional manager",
      "Run a retail store - sales targets, staff, inventory, merchandising and customer experience.",
      S(("Retail Operations","critical"),("Team Management","critical"),("Sales & Targets","important"),
        ("Inventory Management","important"),("Customer Service","important")),
      ["Retail floor experience","Supervisory roles","Store and multi-store management"],
      ["Any degree; retail management diploma helps"],
      ["retail","management","sales","operations"], ["Store","Customer-facing","Leadership"], "Stable"),
    C("field_sales_in", "Sales Executive / Field Sales", "Marketing & Sales", "white", 15000, 120000,
      "Executive to sales manager",
      "Sell products/services to customers - prospecting, pitching, closing and relationship-building - across B2B or B2C.",
      S(("Selling & Negotiation","critical"),("Communication & Persuasion","critical"),("Product Knowledge","important"),
        ("CRM & Follow-up","important"),("Resilience","important")),
      ["Any background - sales rewards skill","Entry sales roles with targets","Grow into sales management"],
      ["Any degree; sales experience matters most"],
      ["sales","field-sales","business","b2b"], ["Field / Office","Target-driven"], "Strong - always in demand"),
    C("insurance_agent_in", "Insurance Agent / Advisor", "Insurance & Actuarial", "no", 12000, 200000,
      "Agent to agency/financial advisor",
      "Advise clients on and sell insurance policies (life, health, general), earning through commissions and renewals.",
      S(("Insurance Products Knowledge","critical"),("Selling & Trust-building","critical"),("Financial Needs Analysis","important"),
        ("Client Service & Renewals","important")),
      ["Clear IRDAI agent exam (insurer-sponsored)","Build a client base","Grow to agency/financial advisory"],
      ["IRDAI agent licence","Any educational background"],
      ["insurance","sales","advisory","self-employment"], ["Field / Remote","Commission-based","Self-employed"], "Stable - large under-insured market"),
    C("call_center_in", "Customer Support / Call Centre Executive", "Business & Management", "pink", 15000, 60000,
      "Associate to team lead/quality analyst",
      "Handle customer queries and support over calls, chat or email - resolving issues and ensuring satisfaction.",
      S(("Communication","critical"),("Problem-solving","critical"),("Product/Process Knowledge","important"),
        ("CRM Tools","important"),("Patience & Empathy","important")),
      ["12th/graduate + good communication","BPO/customer-support roles","Grow to team lead/QA/operations"],
      ["12th pass / graduate; communication skills key"],
      ["customer-support","bpo","call-center","service"], ["Office / Remote","Shift work"], "Stable - large BPO sector"),
    C("management_consultant_in", "Management Consultant", "Business & Management", "white", 50000, 600000,
      "Analyst to partner",
      "Advise organisations on strategy, operations and growth - solving complex business problems with analysis and recommendations.",
      S(("Business Analysis & Strategy","critical"),("Problem Structuring","critical"),("Data Analysis","important"),
        ("Communication & Presentation","important"),("Stakeholder Management","important")),
      ["Strong academics (MBA/engineering helps)","Consulting firm roles","Specialise and rise to partner"],
      ["MBA or strong analytical degree (typical)"],
      ["consulting","strategy","business","analysis"], ["Office / Client-site","High-intensity"], "Strong"),
    C("hr_recruiter_in", "HR Recruiter / Talent Acquisition", "Human Resources", "white", 20000, 150000,
      "Recruiter to TA lead/HRBP",
      "Find, screen and hire talent - sourcing candidates, interviewing and managing the recruitment pipeline.",
      S(("Sourcing & Screening","critical"),("Interviewing","critical"),("ATS & Job Portals","important"),
        ("Stakeholder Management","important"),("Employer Branding","helpful")),
      ["Any degree (HR/MBA helps)","Recruitment agency/in-house roles","Grow to TA lead / HR business partner"],
      ["Any degree; MBA-HR helps"],
      ["hr","recruitment","talent","people"], ["Office / Remote","People-facing"], "Good"),

    # ===================== Office / finance =====================
    C("accountant_bookkeeper_in", "Accountant / Bookkeeper", "Finance", "white", 15000, 100000,
      "Junior accountant to accounts manager",
      "Maintain financial records, ledgers, invoices, GST and reconciliations for businesses - the backbone of every company's finances.",
      S(("Accounting & Bookkeeping","critical"),("Tally/Accounting Software","critical"),("GST & TDS basics","important"),
        ("Reconciliation","important"),("MS Excel","important")),
      ["B.Com or accounting course","Tally/accounting practice","Accounts roles; grow to manager or CA path"],
      ["B.Com / accounting diploma"],
      ["accounting","bookkeeping","finance","tally"], ["Office / Remote","Knowledge work"], "Stable - every business needs it"),
    C("investment_banker_in", "Investment Banker", "Finance", "white", 80000, 1000000,
      "Analyst to managing director",
      "Advise companies on raising capital, mergers and acquisitions - financial modelling, deals and high-stakes finance.",
      S(("Financial Modelling & Valuation","critical"),("Accounting & Finance","critical"),("Deal Analysis","important"),
        ("Excel/PowerPoint","important"),("Stamina & Detail","important")),
      ["Top finance/MBA background","IB analyst roles","Rise through associate to MD"],
      ["MBA (Finance) / CA / strong finance degree"],
      ["investment-banking","finance","m&a","high-finance"], ["Office","High-intensity","Long hours"], "Strong - high pay"),
    C("stockbroker_in", "Stockbroker / Sub-broker", "Trading & Commodities", "no", 15000, 300000,
      "Sub-broker to own broking business",
      "Execute and advise on stock/commodity trades for clients, earning brokerage - increasingly digital with India's retail-investing boom.",
      S(("Markets & Trading Knowledge","critical"),("Client Advisory","important"),("Risk Awareness","important"),
        ("Trading Platforms","important"),("Regulatory Compliance","important")),
      ["Clear NISM certification","Register as sub-broker/authorised person","Build a client book"],
      ["NISM certifications","SEBI registration (via broker)"],
      ["stockbroker","trading","finance","markets"], ["Office / Remote","Self-employed option"], "Growing - retail investing boom"),
    C("office_admin_in", "Office Administrator / Manager", "Business & Management", "white", 15000, 80000,
      "Admin executive to office manager",
      "Keep an office running - scheduling, records, vendors, facilities and support - so everyone else can do their work.",
      S(("Office Coordination","critical"),("MS Office","critical"),("Communication","important"),
        ("Record-keeping","important"),("Time Management","important")),
      ["Any graduate with organisation skills","Admin/front-office roles","Grow to office manager"],
      ["Any degree; computer literacy"],
      ["admin","office","operations","support"], ["Office","Organised"], "Stable"),

    # ===================== Government / public service =====================
    C("police_officer_in", "Police Officer / Sub-Inspector", "Government & Public Service", "white", 25000, 120000,
      "Constable/SI to senior officer",
      "Maintain law and order, prevent and investigate crime, and protect citizens - through state police or central forces.",
      S(("Law & Procedure","critical"),("Physical Fitness","critical"),("Investigation","important"),
        ("Public Interaction","important"),("Discipline & Integrity","critical")),
      ["Clear police recruitment exams (constable/SI) or UPSC for IPS","Physical and written tests","Training academy then service"],
      ["12th/graduate per post; clear recruitment exam + physical"],
      ["police","law-enforcement","government","public-service"], ["Field","Physical","Public-service"], "Stable - govt recruitment"),
    C("firefighter_in", "Firefighter", "Government & Public Service", "blue", 20000, 80000,
      "Fireman to station officer",
      "Respond to fires and emergencies, rescue people, and run prevention and safety operations.",
      S(("Firefighting & Rescue","critical"),("Physical Fitness","critical"),("Emergency Response","critical"),
        ("Equipment Handling","important"),("Teamwork","important")),
      ["Clear fire-service recruitment + physical","Fire training academy","Service and promotions"],
      ["12th pass + physical standards; fire-service recruitment"],
      ["firefighter","emergency","government","public-service"], ["Field","Physical","High-risk"], "Stable"),
    C("railway_loco_pilot_in", "Railway Loco Pilot (Train Driver)", "Transport & Logistics", "blue", 25000, 90000,
      "Assistant loco pilot to loco pilot",
      "Operate trains safely across the railway network - one of India's largest and most sought-after government jobs.",
      S(("Train Operation","critical"),("Signal & Safety Rules","critical"),("Alertness & Stamina","critical"),
        ("Basic Mechanical Knowledge","important")),
      ["ITI/diploma + clear RRB recruitment","Assistant loco pilot, then loco pilot","Railway service"],
      ["ITI/Diploma + RRB recruitment exam"],
      ["railway","loco-pilot","government","transport"], ["Field/Train","Shift work","High-responsibility"], "Stable - govt job"),
    C("forest_officer_in", "Forest Officer / Ranger", "Government & Public Service", "white", 25000, 150000,
      "Forest guard/ranger to IFS officer",
      "Protect forests and wildlife - manage reserves, prevent poaching and illegal logging, and balance conservation with communities.",
      S(("Forestry & Wildlife Knowledge","critical"),("Field & Physical Fitness","critical"),("Law Enforcement (forest)","important"),
        ("Community Engagement","important")),
      ["Forest guard/ranger exams, or UPSC for IFS","Training and field posting","Service and promotions"],
      ["Science graduate (for IFS); recruitment exam + physical"],
      ["forest","wildlife","conservation","government"], ["Field/Outdoor","Physical","Public-service"], "Stable"),

    # ===================== Education =====================
    C("professor_in", "College Professor / Lecturer", "Education & Training", "white", 35000, 200000,
      "Assistant professor to professor",
      "Teach and research at colleges/universities - lectures, mentoring, papers and academic contribution.",
      S(("Subject Expertise","critical"),("Teaching & Pedagogy","critical"),("Research & Publishing","important"),
        ("Mentoring","important"),("Curriculum Design","helpful")),
      ["Master's + clear NET/SET; PhD for higher roles","Assistant professor roles","Rise to associate/full professor"],
      ["Master's + UGC-NET/SET; PhD preferred"],
      ["professor","teaching","academia","education"], ["College","Knowledge work"], "Stable"),
    C("school_teacher_in", "School Teacher", "Education & Training", "white", 18000, 90000,
      "Teacher to senior teacher/coordinator",
      "Teach school students a subject, shape young minds, assess progress and manage classrooms.",
      S(("Subject Knowledge","critical"),("Teaching & Classroom Management","critical"),("Assessment","important"),
        ("Patience & Communication","important"),("Lesson Planning","important")),
      ["B.Ed + subject degree; clear TET/CTET","School teaching roles","Grow to senior teacher/coordinator"],
      ["Graduate + B.Ed; TET/CTET for govt schools"],
      ["teacher","school","education","teaching"], ["School","People-facing"], "Stable"),
    C("special_educator_in", "Special Education Teacher", "Education & Training", "white", 20000, 90000,
      "Special educator to coordinator",
      "Teach and support children with learning, developmental or physical disabilities using individualised methods.",
      S(("Special Education Methods","critical"),("Patience & Empathy","critical"),("Individualised Plans (IEP)","important"),
        ("Behaviour Support","important"),("Parent Collaboration","important")),
      ["B.Ed in Special Education (RCI-recognised)","RCI registration","School/centre roles"],
      ["B.Ed Special Education; RCI registration"],
      ["special-education","teaching","inclusion","education"], ["School/Centre","People-facing"], "Growing - inclusion focus"),
    C("private_tutor_in", "Private Tutor / Online Educator", "Education & Training", "no", 12000, 200000,
      "Home tutor to online educator/edupreneur",
      "Teach students one-on-one or in groups, in person or online - from school subjects to test prep and skills.",
      S(("Subject Mastery","critical"),("Explaining & Simplifying","critical"),("Lesson Planning","important"),
        ("Online Teaching Tools","important"),("Student Motivation","important")),
      ["Strong subject knowledge","Start with local/online students","Scale via YouTube/edtech platforms"],
      ["Subject expertise; teaching ability matters most"],
      ["tutor","teaching","online-education","self-employment"], ["Home / Online","Self-employed option"], "Growing - edtech & tuition demand"),

    # ===================== Creative / media (gaps) =====================
    C("interior_designer_in", "Interior Designer", "Design & Creative", "white", 20000, 200000,
      "Junior designer to own studio",
      "Design functional, beautiful interior spaces for homes and businesses - layouts, materials, lighting and decor.",
      S(("Interior Design & Space Planning","critical"),("CAD/3D Software","important"),("Material & Colour Knowledge","important"),
        ("Client Management","important"),("Project Execution","important")),
      ["Degree/diploma in interior design","Junior roles or assist a designer","Build a portfolio and own studio"],
      ["Degree/Diploma in Interior Design"],
      ["interior-design","creative","design","architecture"], ["Studio/Site","Creative","Self-employed option"], "Good - real estate & renovation"),
    C("journalist_in", "Journalist / Reporter", "Media & Journalism", "white", 18000, 150000,
      "Reporter to editor/correspondent",
      "Research, report and write news stories across print, digital or broadcast - informing the public and holding power to account.",
      S(("Reporting & Research","critical"),("Writing","critical"),("Interviewing","important"),
        ("News Judgement","important"),("Digital/Social Media","helpful")),
      ["Journalism degree or strong writing + clips","Reporting roles at media houses","Specialise (beat) or move to editing"],
      ["Degree (Journalism/Mass Comm helps)"],
      ["journalism","media","writing","news"], ["Field / Newsroom","Knowledge work"], "Stable - shifting to digital"),
    C("social_media_manager_in", "Social Media Manager", "Marketing & Sales", "white", 20000, 150000,
      "Executive to social media/brand lead",
      "Build and run brands' social presence - content, campaigns, community and analytics across platforms.",
      S(("Content Strategy","critical"),("Copywriting & Creatives","important"),("Platform & Trends Knowledge","critical"),
        ("Analytics","important"),("Community Management","important")),
      ["Build your own social presence/portfolio","Agency or in-house roles","Grow to brand/marketing lead"],
      ["Any degree; portfolio and results matter"],
      ["social-media","marketing","content","branding"], ["Office / Remote","Creative"], "Strong - digital marketing growth"),
    C("voice_artist_in", "Voice Artist / Dubbing Artist", "Media & Broadcasting", "no", 15000, 200000,
      "Beginner to sought-after voice talent",
      "Lend your voice to ads, films, dubbing, audiobooks, animation and IVR - a growing field with OTT and regional-content boom.",
      S(("Voice Modulation & Acting","critical"),("Diction & Languages","important"),("Recording Basics","important"),
        ("Script Interpretation","important")),
      ["Train your voice; build a demo reel","Audition for ads/dubbing/animation","Home studio + agency tie-ups"],
      ["No formal degree - voice skill and demo reel"],
      ["voice-artist","dubbing","media","creative"], ["Studio / Remote","Creative","Self-employed option"], "Growing - OTT & dubbing demand"),
    C("interpreter_translator_in", "Translator / Language Specialist", "Language & Diplomacy", "no", 18000, 150000,
      "Freelance to senior translator/localiser",
      "Translate and localise text or speech between languages for documents, media, business and government.",
      S(("Bilingual/Multilingual Fluency","critical"),("Translation & Localisation","critical"),("Subject Vocabulary","important"),
        ("Cultural Nuance","important"),("CAT Tools","helpful")),
      ["Strong command of 2+ languages","Translation diploma/certification","Freelance, agencies, or in-house localisation"],
      ["Language degree/diploma; proven fluency"],
      ["translation","languages","localisation","freelance"], ["Office / Remote","Knowledge work"], "Good - localisation & content"),

    # ===================== Care / personal services =====================
    C("caregiver_in", "Caregiver / Elder Care Attendant", "Mental Health & Therapy", "pink", 12000, 50000,
      "Attendant to senior caregiver/agency",
      "Assist elderly, sick or differently-abled people with daily living, mobility, medication reminders and companionship.",
      S(("Personal & Patient Care","critical"),("Empathy & Patience","critical"),("Basic First Aid","important"),
        ("Hygiene & Mobility Support","important")),
      ["Caregiver/nursing-aide training","Home-care agency or hospital roles","Senior caregiver or run an agency"],
      ["Caregiver/home-health-aide certification (optional)"],
      ["caregiver","elder-care","healthcare","service"], ["Home/Facility","Hands-on","Compassion"], "Growing fast - ageing population"),
    C("massage_therapist_in", "Massage / Spa Therapist", "Beauty & Wellness", "pink", 15000, 80000,
      "Therapist to spa manager/owner",
      "Provide therapeutic and relaxation massages and spa treatments at spas, salons, hotels and wellness centres.",
      S(("Massage Techniques","critical"),("Anatomy basics","important"),("Client Care & Hygiene","important"),
        ("Spa Treatments","important")),
      ["Massage/spa therapy course","Spa/salon/hotel roles","Senior therapist or own setup"],
      ["Massage therapy / spa course certification"],
      ["massage","spa","wellness","beauty"], ["Spa/Salon","Hands-on","Service"], "Good - wellness growth"),
    C("pet_groomer_in", "Pet Groomer", "Veterinary & Animal Care", "no", 15000, 80000,
      "Groomer to own pet-grooming business",
      "Bathe, trim, style and care for pets' coats and hygiene - a fast-growing service with India's rising pet ownership.",
      S(("Pet Grooming & Handling","critical"),("Breed/Coat Knowledge","important"),("Animal Safety & Calm","important"),
        ("Customer Service","helpful")),
      ["Pet grooming course or apprenticeship","Work at a pet salon/clinic","Mobile grooming or own salon"],
      ["Pet grooming course (optional); hands-on skill"],
      ["pet-grooming","animal-care","services","self-employment"], ["Salon/Mobile","Hands-on","Self-employed option"], "Growing fast - pet boom"),
    C("security_guard_in", "Security Guard / Officer", "Everyday Work & Trades", "pink", 12000, 45000,
      "Guard to security supervisor",
      "Protect people, property and premises - access control, patrolling, surveillance and emergency response.",
      S(("Vigilance & Patrolling","critical"),("Access Control","important"),("Emergency Response","important"),
        ("Physical Fitness","important"),("Reporting","helpful")),
      ["Security training (PSARA-compliant agencies)","Guard roles at sites/societies/corporates","Supervisor/officer roles"],
      ["No formal degree; security training; ex-servicemen preferred"],
      ["security","guard","services","safety"], ["Site","Shift work","Physical"], "Stable - large private-security sector"),

    # ===================== Unconventional / niche =====================
    C("tattoo_artist_in", "Tattoo Artist", "Arts & Crafts", "no", 15000, 200000,
      "Apprentice to renowned tattoo artist/studio owner",
      "Design and ink permanent tattoos - blending art skill, hygiene and client trust. A growing urban creative profession.",
      S(("Tattooing & Linework","critical"),("Drawing/Design","critical"),("Hygiene & Sterilisation","critical"),
        ("Client Consultation","important"),("Studio Management","helpful")),
      ["Apprentice under an experienced artist","Build a portfolio and hygiene practice","Studio artist or own studio"],
      ["No formal degree - apprenticeship and portfolio; hygiene training"],
      ["tattoo","art","creative","self-employment"], ["Studio","Creative","Self-employed option"], "Growing - urban acceptance rising"),
    C("private_investigator_in", "Private Investigator / Detective", "Forensic & Investigation", "no", 20000, 150000,
      "Investigator to own detective agency",
      "Conduct discreet investigations - background checks, surveillance, fraud, matrimonial and corporate cases - for private clients.",
      S(("Surveillance & Investigation","critical"),("Discretion & Ethics","critical"),("Evidence Gathering","important"),
        ("Report Writing","important"),("People & Tech Tools","helpful")),
      ["Learn under an agency or from a law/police background","Build cases and clientele","Run a detective agency"],
      ["No fixed degree; investigation training; ex-police/army valued"],
      ["detective","investigation","forensic","self-employment"], ["Field","Discreet","Self-employed option"], "Niche - steady private demand"),
    C("calligrapher_in", "Calligrapher / Lettering Artist", "Arts & Crafts", "no", 10000, 100000,
      "Hobbyist to commissioned lettering artist",
      "Create beautiful hand-lettering and calligraphy for invitations, branding, art and events - across Devanagari, Urdu and modern scripts.",
      S(("Calligraphy & Lettering","critical"),("Script Knowledge","important"),("Design Sense","important"),
        ("Commission/Client Work","helpful"),("Social Media Showcasing","helpful")),
      ["Practise scripts and build a portfolio","Take commissions (weddings, brands, art)","Workshops as added income"],
      ["No formal degree - skill and portfolio"],
      ["calligraphy","lettering","art","creative"], ["Studio / Remote","Creative","Self-employed option"], "Niche - design & events demand"),
    C("life_coach_in", "Life Coach / Personal Development Coach", "Mental Health & Therapy", "no", 20000, 250000,
      "New coach to established personal brand",
      "Help clients set and reach personal and professional goals through structured coaching, accountability and motivation.",
      S(("Coaching & Active Listening","critical"),("Goal-setting Frameworks","important"),("Empathy & Communication","critical"),
        ("Personal Branding","important"),("Content Creation","helpful")),
      ["Coaching certification (ICF-aligned helps)","Build a niche and client base","Scale via content, courses, workshops"],
      ["Coaching certification (optional); credibility matters"],
      ["life-coach","coaching","personal-development","self-employment"], ["Online / Remote","Self-employed option"], "Growing - self-improvement market"),
    C("nutritionist_in", "Nutritionist / Diet Consultant", "Food Science & Nutrition", "no", 18000, 150000,
      "Consultant to own nutrition practice",
      "Advise clients on diet and nutrition for health, weight, sports or medical needs - increasingly online and subscription-based.",
      S(("Nutrition Science","critical"),("Diet Planning","critical"),("Client Counselling","important"),
        ("Health Assessment","important"),("Online Coaching","helpful")),
      ["B.Sc/M.Sc Nutrition & Dietetics or certification","Clinic/gym/online roles","Own practice / app-based coaching"],
      ["B.Sc/M.Sc in Nutrition & Dietetics (or certification)"],
      ["nutrition","diet","wellness","health"], ["Clinic / Online","Self-employed option"], "Growing - health & fitness trend"),
]


def main():
    with open(PATH, encoding="utf-8") as f:
        existing = json.load(f)
    ids = {c["id"] for c in existing}
    titles = {c["title"].strip().lower() for c in existing}

    to_add = []
    for c in NEW:
        if c["id"] in ids:
            print("SKIP id:", c["id"]); continue
        if c["title"].strip().lower() in titles:
            print("SKIP title:", c["title"]); continue
        ids.add(c["id"]); titles.add(c["title"].strip().lower())
        to_add.append(c)
    if not to_add:
        print("Nothing new."); return

    with open(PATH, encoding="utf-8") as f:
        text = f.read()
    idx = text.rstrip().rfind("]")
    head = text.rstrip()[:idx].rstrip()
    chunks = ["\n".join("  " + ln for ln in json.dumps(c, ensure_ascii=False, indent=2).splitlines()) for c in to_add]
    new_text = head + ",\n" + ",\n".join(chunks) + "\n]\n"
    parsed = json.loads(new_text)
    assert len(parsed) == len(existing) + len(to_add)
    with open(PATH, "w", encoding="utf-8") as f:
        f.write(new_text)
    print(f"Added {len(to_add)}. Total now {len(parsed)}.")


if __name__ == "__main__":
    main()
