# Copyright (c) 2025-2026 K.N.Narin. Non-commercial use only. See LICENSE.
"""Append a curated batch of India-focused and unconventional careers to
careers.json. Append-only (textual insert) so existing entries' bytes are never
re-encoded — important given the file's known UTF-8 sensitivity. ASCII-only text.

Run from repo root:  python scripts/add_india_unconventional.py
"""
import json
import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PATH = os.path.join(HERE, "backend", "data", "careers.json")


def C(cid, title, category, collar, smin, smax, note, desc, skills, paths, quals, tags, work, growth):
    return {
        "id": cid,
        "title": title,
        "category": category,
        "region": "IN",
        "description": desc,
        "salary_range": {"min": smin, "max": smax, "currency": "INR/month", "note": note},
        "growth_outlook": growth,
        "work_style": work,
        "required_skills": [{"skill": s, "level": l} for s, l in skills],
        "entry_paths": paths,
        "qualifications": quals,
        "tags": tags,
        "collar": collar,
    }


NEW = [
    # ---------- Textile, saree & ethnic wear ----------
    C("saree_weaver_in", "Handloom Saree Weaver", "Arts & Crafts", "blue",
      12000, 60000, "Karigar wages to master weaver running own looms",
      "Weave traditional sarees such as Banarasi, Kanjeevaram, Pochampally or Chanderi on handlooms. A heritage craft with strong demand from premium and export markets, and government weaver schemes.",
      [("Handloom Weaving (pit/frame loom)", "critical"), ("Traditional Motif & Pattern Design", "critical"),
       ("Yarn Dyeing & Preparation", "important"), ("Zari / Brocade Work", "important"),
       ("Quality Finishing", "important"), ("Costing & Selling to Buyers", "helpful")],
      ["Learn under a master weaver in a weaving cluster (Varanasi, Kanchipuram, Pochampally)",
       "Join a weavers' cooperative society or SHG",
       "Apply for handloom development schemes and weaver credit cards"],
      ["No formal degree required - apprenticeship under a master weaver",
       "Diploma in Handloom Technology (IIHT) optional for supervisory roles"],
      ["handloom", "saree", "weaving", "textile", "heritage-craft", "self-employment"],
      ["Home-based / Workshop", "Self-employed", "Skilled craft"], "Stable - premium and export demand for authentic handloom"),

    C("saree_retailer_in", "Saree Retail Entrepreneur", "Entrepreneurship & MSME", "no",
      20000, 300000, "Small shop to multi-store or online saree business",
      "Run a saree retail business - physical store, exhibitions, or online (Instagram/WhatsApp/marketplace). Sourcing directly from weaving clusters and selling to end customers is a popular low-capital business across India.",
      [("Sourcing from Weaving Clusters", "critical"), ("Sales & Customer Relationship", "critical"),
       ("Inventory & Working Capital Management", "important"), ("Social Media Selling (Reels/Live)", "important"),
       ("Pricing & Margins", "important"), ("Basic Accounting/GST", "helpful")],
      ["Start small sourcing from wholesale hubs (Surat, Varanasi, Kanchipuram)",
       "Sell via Instagram/WhatsApp before opening a physical store",
       "Register MSME (Udyam) and GST for wholesale supply"],
      ["No formal qualification required", "MSME / Udyam registration for credit and benefits"],
      ["saree", "retail", "ethnic-wear", "small-business", "self-employment"],
      ["Self-employed", "Customer-facing", "Online + Offline"], "Growing - social commerce expanding reach"),

    C("boutique_designer_in", "Boutique Owner / Ethnic Wear Designer", "Fashion & Apparel", "no",
      25000, 400000, "Home boutique to established designer label",
      "Design and tailor custom ethnic and fusion wear - lehengas, kurtas, blouses, bridal outfits - and run a boutique. Combines design sense with tailoring and client management.",
      [("Garment Design & Sketching", "critical"), ("Tailoring & Pattern Making", "critical"),
       ("Fabric & Trend Knowledge", "important"), ("Client Consultation & Fitting", "important"),
       ("Embroidery & Embellishment", "important"), ("Boutique Marketing", "helpful")],
      ["Diploma in fashion design or apprenticeship with a designer/tailor",
       "Start a home boutique and grow via word of mouth and Instagram",
       "Tie up with local tailors and karigars for volume"],
      ["Diploma/Degree in Fashion Design (NIFT, NID, or private institute) - optional",
       "Tailoring certification or hands-on apprenticeship"],
      ["boutique", "fashion", "ethnic-wear", "design", "self-employment"],
      ["Self-employed", "Creative", "Customer-facing"], "Good - strong wedding and festive market"),

    C("zardozi_artisan_in", "Zardozi & Zari Embroidery Artisan", "Arts & Crafts", "blue",
      12000, 70000, "Karigar to master embroiderer with own unit",
      "Practise Zardozi/Zari hand embroidery - metallic thread, bead and stone work on bridal and couture garments. A Mughal-era craft central to India's luxury fashion and export houses.",
      [("Zardozi / Aari Hand Embroidery", "critical"), ("Thread, Bead & Stone Work", "critical"),
       ("Design Tracing & Frame (Adda) Work", "important"), ("Finishing & Quality", "important"),
       ("Working with Designers/Export Houses", "helpful")],
      ["Apprentice under a master karigar in Lucknow, Delhi or Mumbai embroidery units",
       "Join an export house or couture designer's karkhana",
       "Set up own adda unit and take job-work orders"],
      ["No formal degree - traditional apprenticeship",
       "Craft certification from a handicraft board (optional)"],
      ["zardozi", "embroidery", "zari", "handicraft", "couture", "heritage-craft"],
      ["Workshop-based", "Skilled craft", "Team or self-employed"], "Stable - couture and export demand"),

    # ---------- Jewellery crafts ----------
    C("kundan_meenakari_in", "Kundan & Meenakari Jewellery Maker", "Gemology & Jewelry", "blue",
      15000, 120000, "Karigar to independent jewellery artisan/brand",
      "Craft traditional Kundan, Polki and Meenakari (enamel) jewellery by hand - a Rajasthani/Mughal heritage craft with high value in bridal and luxury markets.",
      [("Kundan Setting (gold foil & stones)", "critical"), ("Meenakari Enamelling", "critical"),
       ("Goldsmithing Basics", "important"), ("Design & Motif Knowledge", "important"),
       ("Stone Selection & Grading", "helpful"), ("Selling / Branding", "helpful")],
      ["Apprentice in a Jaipur or Bikaner jewellery workshop",
       "Learn goldsmithing then specialise in Kundan/Meena work",
       "Build an Instagram/boutique brand for direct sales"],
      ["Traditional apprenticeship under a master karigar",
       "Jewellery design course (optional, e.g. from a gem & jewellery institute)"],
      ["jewellery", "kundan", "meenakari", "handicraft", "heritage-craft", "self-employment"],
      ["Workshop-based", "Skilled craft", "Self-employed"], "Good - bridal and luxury jewellery demand"),

    C("bangle_maker_in", "Lac & Glass Bangle Maker", "Arts & Crafts", "blue",
      10000, 45000, "Artisan wages to small bangle workshop owner",
      "Make traditional lac (lakh) and glass bangles - shaping, colouring and embellishing - a craft concentrated in Firozabad and Rajasthan with festive and bridal demand.",
      [("Lac/Glass Bangle Shaping", "critical"), ("Colouring & Stone Embellishment", "critical"),
       ("Heat & Mould Handling", "important"), ("Design Variety", "important"),
       ("Wholesale Selling", "helpful")],
      ["Apprentice in a Firozabad or Jaipur bangle unit",
       "Family craft transfer / SHG training",
       "Supply to wholesalers or sell at melas and online"],
      ["No formal degree - hands-on apprenticeship", "Craft/SHG training programme (optional)"],
      ["bangles", "lac", "handicraft", "festive", "self-employment"],
      ["Workshop-based", "Skilled craft", "Self-employed"], "Stable - festive and bridal demand"),

    # ---------- Spiritual & occult ----------
    C("numerologist_in", "Numerologist", "Spiritual & Religious", "no",
      15000, 300000, "Local practice to celebrity numerologist with online following",
      "Advise clients using numerology - name/number analysis, lucky numbers, name-correction and business naming - increasingly popular via apps, YouTube and matrimony/branding consults.",
      [("Numerology Systems (Pythagorean/Chaldean)", "critical"), ("Name & Date Analysis", "critical"),
       ("Client Counselling & Empathy", "critical"), ("Report Writing", "important"),
       ("Digital Content / Social Reach", "helpful")],
      ["Learn from a guru or certified numerology course",
       "Start free readings to build reputation, then charge consults",
       "Build a YouTube/Instagram presence and join astro platforms"],
      ["Numerology certification/diploma (private institutes) - optional",
       "No formal degree required for private practice"],
      ["numerology", "spiritual", "consulting", "self-employment", "occult"],
      ["Consulting", "Online / Remote", "Self-employed"], "Growing - digital astrology/occult market expanding"),

    C("palmist_in", "Palmist (Hast Rekha Shastra)", "Spiritual & Religious", "no",
      12000, 250000, "Local readings to established palmistry consultant",
      "Read palms (Hast Rekha) - lines, mounts and hand shape - for guidance on career, relationships and health, often alongside astrology. Demand at fairs, online and private consults.",
      [("Palmistry (lines, mounts, hand types)", "critical"), ("Client Reading & Counselling", "critical"),
       ("Astrology basics (complementary)", "helpful"), ("Communication & Empathy", "critical"),
       ("Social Media Presence", "helpful")],
      ["Study under an experienced palmist or via books/courses",
       "Practise readings at fairs/exhibitions to gain experience",
       "Offer online consultations and build a following"],
      ["No formal degree - apprenticeship/self-study",
       "Palmistry course certificate (optional)"],
      ["palmistry", "hast-rekha", "spiritual", "consulting", "occult"],
      ["Consulting", "Online / Remote", "Self-employed"], "Stable to growing - steady traditional demand"),

    C("tarot_reader_in", "Tarot Card Reader", "Spiritual & Religious", "no",
      15000, 250000, "Part-time readings to full-time tarot consultant/creator",
      "Give tarot card readings for guidance on love, career and decisions - a fast-growing urban and online practice among younger Indians, popular on Instagram and consultation apps.",
      [("Tarot Card Systems & Spreads", "critical"), ("Intuitive Reading & Storytelling", "critical"),
       ("Client Counselling & Empathy", "critical"), ("Content Creation (Reels/YouTube)", "important"),
       ("Booking & Online Tools", "helpful")],
      ["Take a tarot certification course or learn from a mentor",
       "Practise with friends, then offer paid online readings",
       "Grow via Instagram Reels and consultation platforms"],
      ["Tarot certification (private/online) - optional",
       "No formal degree required"],
      ["tarot", "spiritual", "consulting", "content-creator", "occult"],
      ["Consulting", "Online / Remote", "Self-employed"], "Growing fast - popular with urban youth online"),

    C("reiki_healer_in", "Reiki / Pranic Healer", "Mental Health & Therapy", "no",
      15000, 200000, "Part-time healer to wellness-centre practitioner/trainer",
      "Practise energy healing (Reiki, Pranic Healing) for stress, wellness and relaxation - often combined with meditation and offered at wellness centres or independently.",
      [("Reiki / Pranic Healing Levels", "critical"), ("Energy & Chakra Knowledge", "critical"),
       ("Client Counselling & Empathy", "critical"), ("Meditation Guidance", "important"),
       ("Wellness Marketing", "helpful")],
      ["Get attuned and certified through Reiki Levels 1-3 / Master under a teacher",
       "Practise on clients and at wellness centres",
       "Offer distance healing and workshops online"],
      ["Reiki Level certifications (I, II, Master)", "Pranic Healing course (optional)",
       "No formal degree required"],
      ["reiki", "healing", "wellness", "spiritual", "self-employment"],
      ["Consulting", "Wellness centre", "Self-employed"], "Growing - wellness and holistic health demand"),

    C("mehndi_artist_in", "Mehndi / Henna Artist", "Beauty & Wellness", "no",
      15000, 150000, "Per-function fees to bridal mehndi brand with a team",
      "Apply mehndi (henna) designs for weddings, festivals and events - bridal, Arabic, and contemporary styles. High festive/wedding-season demand and strong social-media discoverability.",
      [("Mehndi Design (bridal/Arabic/Indo-Arabic)", "critical"), ("Cone Control & Speed", "critical"),
       ("Trend & Pattern Knowledge", "important"), ("Client Handling & Booking", "important"),
       ("Instagram Portfolio Building", "important")],
      ["Practise extensively and build a design portfolio",
       "Start with small events, then bridal bookings",
       "Promote on Instagram and tie up with wedding planners"],
      ["No formal degree - skill and portfolio matter most",
       "Mehndi/beauty course certificate (optional)"],
      ["mehndi", "henna", "bridal", "beauty", "self-employment", "creative"],
      ["Event-based", "Self-employed", "Creative"], "Good - steady wedding and festive demand"),

    C("rangoli_artist_in", "Rangoli & Floor Art Artist", "Arts & Crafts", "no",
      10000, 120000, "Per-event fees to commissioned festive art business",
      "Create rangoli and floor art for festivals, weddings, events and brand activations - including large 3D and themed rangolis. Seasonal but high-visibility creative work.",
      [("Rangoli Design & Colour Work", "critical"), ("Large-format & 3D Rangoli", "important"),
       ("Speed & Precision", "important"), ("Event Coordination", "helpful"),
       ("Social Media Showcasing", "important")],
      ["Build a portfolio of festival and event rangolis",
       "Offer services for Diwali/Onam/weddings and corporate events",
       "Share time-lapse videos on social media to get bookings"],
      ["No formal qualification - creativity and portfolio",
       "Fine arts background (optional)"],
      ["rangoli", "floor-art", "festive", "creative", "self-employment"],
      ["Event-based", "Self-employed", "Creative"], "Stable - festive and event demand"),

    # ---------- Folk & performing arts ----------
    C("classical_dancer_in", "Classical Dancer (Bharatanatyam / Kathak)", "Arts & Performance", "no",
      15000, 200000, "Performance fees + teaching; varies widely by reputation",
      "Perform and teach Indian classical dance such as Bharatanatyam, Kathak, Odissi or Kuchipudi. Income blends stage performances, teaching a dance school, choreography and cultural programmes.",
      [("Classical Dance Technique (a specific style)", "critical"), ("Abhinaya & Expression", "critical"),
       ("Rhythm (Tala) & Music Knowledge", "important"), ("Choreography", "important"),
       ("Teaching & Running a Dance School", "helpful")],
      ["Train for years under a guru (guru-shishya parampara)",
       "Complete graded exams / Arangetram (debut performance)",
       "Build income via performances, teaching and cultural bodies"],
      ["Visharad / degree in dance (e.g. from a music-dance university) - optional but respected",
       "Years of guru-led training and a public debut (Arangetram)"],
      ["dance", "classical", "performing-arts", "teaching", "heritage"],
      ["Performance + Teaching", "Self-employed", "Creative"], "Stable - cultural and teaching demand"),

    C("folk_artist_in", "Folk Artist / Lok Kalakar", "Arts & Performance", "no",
      10000, 100000, "Programme fees; supported by govt cultural schemes",
      "Perform regional folk art forms - dance, music, theatre such as Bhavai, Lavani, Bihu, Garba, or storytelling - at festivals, tourism events and cultural programmes, often with government and tourism support.",
      [("A Folk Art Form (regional)", "critical"), ("Stage Performance", "critical"),
       ("Traditional Music/Instruments", "important"), ("Costume & Presentation", "helpful"),
       ("Event & Tourism Networking", "helpful")],
      ["Learn the form within community/family tradition",
       "Register with cultural/tourism departments and Sangeet Natak Akademi",
       "Perform at festivals, tourism circuits and cultural exchanges"],
      ["No formal degree - community/traditional training",
       "Empanelment with cultural bodies (ICCR, state akademis)"],
      ["folk-art", "performing-arts", "culture", "heritage", "self-employment"],
      ["Performance", "Self-employed", "Creative"], "Stable - government and tourism patronage"),

    C("dhol_percussion_in", "Dhol / Percussion Artist", "Music Industry", "no",
      12000, 150000, "Per-event fees to busy wedding/event percussionist",
      "Play dhol, nagada, or other percussion at weddings, processions, festivals and events. High demand in the wedding and DJ/event circuit, especially in North and West India.",
      [("Dhol / Percussion Playing", "critical"), ("Rhythm & Stamina", "critical"),
       ("Repertoire (wedding/festival beats)", "important"), ("Stage Energy & Showmanship", "important"),
       ("Event Networking", "helpful")],
      ["Learn from senior players / community groups",
       "Join a dhol/baraat troupe for events",
       "Build bookings via wedding planners and social media"],
      ["No formal degree - apprenticeship and practice",
       "Music school percussion training (optional)"],
      ["dhol", "percussion", "music", "wedding", "self-employment"],
      ["Event-based", "Self-employed", "Creative"], "Good - strong wedding/event demand"),

    C("puppeteer_in", "Puppeteer (Kathputli & Modern)", "Arts & Performance", "no",
      10000, 90000, "Show fees; supplemented by workshops and tourism",
      "Perform and craft puppets - traditional Kathputli string puppets or modern puppetry - for shows, education, tourism and media. A niche heritage art with workshop and edutainment demand.",
      [("Puppet Performance & Manipulation", "critical"), ("Puppet Making", "important"),
       ("Storytelling & Voice", "important"), ("Workshop Facilitation", "helpful"),
       ("Event/Tourism Networking", "helpful")],
      ["Learn within a puppeteer community (e.g. Rajasthan) or arts org",
       "Perform at schools, fairs, tourism and cultural events",
       "Run puppet-making workshops as an added income stream"],
      ["No formal degree - traditional/community training",
       "Theatre or fine-arts background (optional)"],
      ["puppetry", "kathputli", "performing-arts", "heritage", "self-employment"],
      ["Performance + Workshops", "Self-employed", "Creative"], "Niche - heritage and edutainment demand"),

    # ---------- Adventure, sports & unconventional physical ----------
    C("equestrian_instructor_in", "Equestrian / Horse Riding Instructor", "Sports & Athletics", "no",
      20000, 150000, "Riding school instructor to own stable/academy",
      "Train riders and care for horses at riding schools, clubs, resorts and for equestrian sport. Combines coaching, horse management and sometimes competition or wedding/film horse work.",
      [("Horse Riding & Training", "critical"), ("Horse Care & Stable Management", "critical"),
       ("Coaching & Safety", "important"), ("Competition/Dressage (for sport track)", "helpful"),
       ("Client & Resort Liaison", "helpful")],
      ["Train at a riding school / cavalry or police equestrian background",
       "Get coaching experience at clubs or resorts",
       "Build towards running your own stable or academy"],
      ["Equestrian Federation of India coaching credentials (for sport)",
       "No formal degree required - skill and experience matter"],
      ["equestrian", "horse-riding", "sports", "coaching", "self-employment"],
      ["Outdoor", "Coaching", "Self-employed or club"], "Niche but growing - clubs, resorts and sport"),

    C("stunt_performer_in", "Stunt Performer / Action Choreographer", "Film & Entertainment", "no",
      25000, 500000, "Per-shoot fees; top action directors earn much more",
      "Perform film/TV stunts and choreograph action sequences - fights, falls, fire, vehicle and wire work. High-skill, high-risk work in film, OTT, ads and events.",
      [("Stunt & Action Skills (martial arts/gymnastics)", "critical"), ("Safety & Rigging", "critical"),
       ("Fitness & Conditioning", "critical"), ("Action Choreography", "important"),
       ("Film Set Coordination", "helpful")],
      ["Train in martial arts/gymnastics and join a stunt union/team",
       "Start as a junior stunt artist and build credits",
       "Progress to action choreographer/director"],
      ["Stunt training and union membership (e.g. Movie Stunt Artists Association)",
       "No formal degree - physical skill and safety record matter"],
      ["stunts", "action", "film", "fitness", "self-employment"],
      ["Project-based", "High-risk", "Physical"], "Good - growing film/OTT/ad production"),

    C("adventure_guide_in", "Mountaineering / Trekking Guide", "Sports & Athletics", "no",
      18000, 150000, "Seasonal guiding to running an adventure travel firm",
      "Lead treks, mountaineering expeditions and adventure tours in the Himalayas and beyond, ensuring safety and a great experience. Demand driven by India's booming adventure-tourism market.",
      [("Mountaineering & Trekking Skills", "critical"), ("Wilderness First Aid & Safety", "critical"),
       ("Navigation & Weather Reading", "important"), ("Group Leadership", "important"),
       ("Tour Logistics & Hospitality", "helpful")],
      ["Complete courses at NIM/HMI/ABVIMAS mountaineering institutes",
       "Guide with established adventure operators",
       "Build towards leading expeditions or your own travel firm"],
      ["Basic/Advanced Mountaineering Course (NIM, HMI, ABVIMAS)",
       "Wilderness first-aid certification"],
      ["mountaineering", "trekking", "adventure", "tourism", "outdoor", "self-employment"],
      ["Outdoor", "Seasonal", "Physical"], "Growing - adventure tourism boom"),

    C("scuba_instructor_in", "Scuba Diving Instructor", "Sports & Athletics", "no",
      25000, 200000, "Resort instructor to dive-centre owner",
      "Teach and guide scuba diving at coastal/island destinations (Andamans, Goa, Lakshadweep) - certifying divers and leading dives. Tied to coastal tourism growth.",
      [("Scuba Diving & Instruction (PADI/SSI)", "critical"), ("Underwater Safety & Rescue", "critical"),
       ("Swimming & Fitness", "critical"), ("Equipment Maintenance", "important"),
       ("Tourist Handling", "helpful")],
      ["Progress through PADI/SSI: Open Water -> Divemaster -> Instructor",
       "Work at a dive centre in a coastal destination",
       "Build towards owning a dive centre"],
      ["PADI/SSI Instructor certification", "Strong swimming ability; medical fitness"],
      ["scuba", "diving", "adventure", "tourism", "coastal", "self-employment"],
      ["Outdoor / Water", "Seasonal", "Physical"], "Growing - coastal adventure tourism"),

    C("wildlife_photographer_in", "Wildlife Photographer", "Photography & Visual Media", "no",
      20000, 300000, "Assignments + prints/stock; varies with reputation",
      "Photograph wildlife and nature for magazines, documentaries, stock, NGOs and prints, often working from India's national parks and sanctuaries. Income mixes assignments, workshops, stock and tours.",
      [("Wildlife & Nature Photography", "critical"), ("Field Craft & Patience", "critical"),
       ("Photo Editing", "important"), ("Knowledge of Species & Habitats", "important"),
       ("Selling Stock / Running Tours", "helpful")],
      ["Build a strong portfolio at national parks and sanctuaries",
       "Sell to magazines, stock platforms and NGOs",
       "Run photography tours and workshops for steady income"],
      ["No formal degree - portfolio is the credential",
       "Photography course or naturalist training (optional)"],
      ["wildlife", "photography", "nature", "creative", "self-employment"],
      ["Outdoor", "Project-based", "Self-employed"], "Niche - conservation media and tourism"),

    C("snake_rescuer_in", "Wildlife Rescuer / Snake Catcher", "Veterinary & Animal Care", "no",
      12000, 80000, "Often honorarium/NGO-paid; some run rescue services",
      "Rescue and safely relocate snakes and urban wildlife, educate communities, and assist forest departments. A specialised, public-service-oriented field tied to conservation and human-wildlife conflict.",
      [("Snake/Wildlife Handling & Safety", "critical"), ("Species Identification", "critical"),
       ("First Response & Relocation", "important"), ("Community Education", "important"),
       ("Coordination with Forest Dept", "helpful")],
      ["Train with experienced rescuers and herpetology groups",
       "Volunteer with NGOs and forest department",
       "Build a recognised rescue service in your area"],
      ["No formal degree - hands-on training and safety record",
       "Forest department recognition / wildlife NGO training"],
      ["wildlife", "snake-rescue", "conservation", "animal-care", "public-service"],
      ["Outdoor", "On-call", "Public-service"], "Niche - rising urban wildlife conflict"),

    C("chess_coach_in", "Chess Coach / Professional Player", "Gaming & Esports", "no",
      15000, 250000, "Coaching + tournament income; titled players earn more",
      "Coach chess and/or compete professionally - a fast-growing field in India after its world-stage success, with strong demand for academies, online coaching and school programmes.",
      [("Advanced Chess Play & Theory", "critical"), ("Coaching & Curriculum", "critical"),
       ("Game Analysis (engines/databases)", "important"), ("Online Coaching Tools", "important"),
       ("Tournament Experience", "helpful")],
      ["Earn a rating/title via tournaments (AICF/FIDE)",
       "Coach at academies, schools and online platforms",
       "Build an online coaching brand"],
      ["FIDE rating/title (helpful)", "AICF arbiter/coach certification (optional)",
       "No formal degree required"],
      ["chess", "coaching", "sports", "online-coaching", "self-employment"],
      ["Coaching", "Online / Remote", "Self-employed"], "Growing fast - chess boom in India"),

    # ---------- Rural & agri entrepreneurship ----------
    C("beekeeper_in", "Beekeeper / Apiculturist", "Agriculture & Farming", "no",
      15000, 120000, "Small apiary to honey brand with distribution",
      "Keep bees for honey and hive products, pollination services and value-added products. Supported by government apiculture missions and rising demand for natural honey.",
      [("Beekeeping & Hive Management", "critical"), ("Honey Extraction & Processing", "critical"),
       ("Pest/Disease Management", "important"), ("Packaging & Branding", "important"),
       ("Marketing/Selling Honey", "helpful")],
      ["Train via KVK / National Bee Board / agri-university programmes",
       "Start with a few hives and scale up",
       "Build a brand and sell direct + via FPOs/markets"],
      ["Beekeeping training (KVK, National Bee Board)",
       "No formal degree required"],
      ["beekeeping", "apiculture", "agriculture", "agripreneur", "self-employment"],
      ["Outdoor / Farm", "Self-employed", "Entrepreneurial"], "Growing - natural honey demand and govt support"),

    C("mushroom_farmer_in", "Mushroom Farming Entrepreneur", "Agriculture & Farming", "no",
      15000, 150000, "Small unit to commercial mushroom supply business",
      "Grow mushrooms (button, oyster, milky) in controlled conditions and supply to markets, restaurants and processors. Low land requirement and quick cycles make it popular for rural/peri-urban entrepreneurs.",
      [("Mushroom Cultivation & Spawn Management", "critical"), ("Climate/Hygiene Control", "critical"),
       ("Harvest & Post-harvest Handling", "important"), ("Marketing & Supply", "important"),
       ("Basic Costing", "helpful")],
      ["Train at KVK / agri-university mushroom courses",
       "Start a small grow room and secure local buyers",
       "Scale to commercial supply and value-added products"],
      ["Mushroom cultivation training (KVK, agri-university)",
       "No formal degree required"],
      ["mushroom", "farming", "agriculture", "agripreneur", "self-employment"],
      ["Farm / Indoor", "Self-employed", "Entrepreneurial"], "Growing - high-value, low-land agribusiness"),

    C("organic_farmer_in", "Organic Farming Agripreneur", "Agriculture & Farming", "no",
      15000, 200000, "Smallholder to organic brand with FPO/exports",
      "Grow and market organic/natural produce, often building a direct-to-consumer brand or supplying FPOs and exporters. Driven by health-conscious demand and government organic missions.",
      [("Organic/Natural Farming Practices", "critical"), ("Soil & Pest Management (organic)", "critical"),
       ("Certification & Compliance", "important"), ("Direct Marketing / D2C", "important"),
       ("Farm Record-keeping", "helpful")],
      ["Train via organic farming missions / KVKs",
       "Convert land and obtain organic certification",
       "Build a D2C brand or supply FPOs and exporters"],
      ["Organic certification (e.g. PGS/India Organic)",
       "Agriculture diploma/degree (optional)"],
      ["organic", "farming", "agriculture", "agripreneur", "sustainability", "self-employment"],
      ["Farm", "Self-employed", "Entrepreneurial"], "Growing - organic and natural food demand"),

    # ---------- Modern Indian professions ----------
    C("upsc_mentor_in", "UPSC / Civil Services Mentor", "Education & Training", "white",
      30000, 500000, "Faculty to star educator/edtech founder",
      "Coach aspirants for UPSC and state civil-services exams - teaching, mentoring, test series and content. A large, prestige-driven market across coaching hubs and online platforms.",
      [("Subject Mastery (GS/optional)", "critical"), ("Exam Strategy & Answer Writing", "critical"),
       ("Teaching & Mentoring", "critical"), ("Content/Test-series Creation", "important"),
       ("Online Teaching Tools", "helpful")],
      ["Strong exam performance or deep subject expertise",
       "Teach at coaching institutes or online platforms",
       "Build a personal brand via YouTube/Telegram"],
      ["Postgraduate degree in the subject (typical)",
       "UPSC/state-services attempt experience (valued)"],
      ["upsc", "civil-services", "teaching", "mentoring", "edtech"],
      ["Teaching", "Online + Offline", "Knowledge work"], "Strong - large, prestige-driven aspirant base"),

    C("company_secretary_in", "Company Secretary (CS)", "Legal & Justice", "white",
      35000, 300000, "Trainee to senior CS / governance head",
      "Ensure corporate legal and regulatory compliance, board governance and secretarial standards under the Companies Act. A statutory profession with steady corporate demand.",
      [("Company Law & Compliance", "critical"), ("Corporate Governance & Board Process", "critical"),
       ("Secretarial Standards & Filings", "critical"), ("Drafting (resolutions/agreements)", "important"),
       ("SEBI/Listing Regulations", "important")],
      ["Clear ICSI's CS programme (Foundation/Executive/Professional)",
       "Complete practical training",
       "Work in corporates, CS firms or independent practice"],
      ["ICSI Company Secretary qualification (Professional)",
       "ACS membership of ICSI"],
      ["company-secretary", "compliance", "corporate-law", "governance", "finance"],
      ["Office", "Corporate", "Knowledge work"], "Stable - statutory corporate requirement"),

    C("gst_consultant_in", "GST & Taxation Consultant", "Finance", "no",
      20000, 250000, "Independent practice to tax advisory firm",
      "Help businesses with GST registration, returns, reconciliations, income tax and compliance. High demand from India's vast MSME base after GST rollout.",
      [("GST Law & Returns", "critical"), ("Income Tax Compliance", "critical"),
       ("Accounting & Reconciliation", "important"), ("Tax Software (Tally/Portals)", "important"),
       ("Client Advisory", "important")],
      ["Commerce background + GST/tax certification courses",
       "Start with small businesses and shops",
       "Build a practice or join a CA/tax firm"],
      ["B.Com or commerce background (typical)",
       "GST practitioner certification; CA/CMA (optional, higher-end)"],
      ["gst", "taxation", "compliance", "finance", "self-employment"],
      ["Office / Remote", "Self-employed", "Knowledge work"], "Strong - large MSME compliance market"),

    C("drone_pilot_in", "Drone Pilot / Agri-Drone Operator", "Aviation & Airport", "no",
      20000, 200000, "Operator to drone-services business owner",
      "Fly drones for agriculture (spraying/mapping), surveying, inspection, photography and deliveries. A fast-emerging field backed by India's drone policy and agri-drone schemes.",
      [("Drone Piloting & Safety", "critical"), ("DGCA Regulations & Compliance", "critical"),
       ("Mission Planning / Mapping", "important"), ("Maintenance & Troubleshooting", "important"),
       ("Data/Imagery Handling", "helpful")],
      ["Get DGCA-approved RPC/remote pilot certificate from an RPTO",
       "Specialise (agri-spraying, survey, inspection, media)",
       "Offer drone services or join an operator"],
      ["DGCA Remote Pilot Certificate (from approved RPTO)",
       "No degree required; technical aptitude helps"],
      ["drone", "agri-tech", "aviation", "emerging-tech", "self-employment"],
      ["Field", "Self-employed or firm", "Technical"], "Growing fast - drone policy and agri-drone push"),

    C("ev_technician_in", "EV Service Technician", "Automotive & EV", "blue",
      18000, 90000, "Technician to EV workshop owner",
      "Service and repair electric vehicles - batteries, motors, controllers and charging systems. Demand is rising sharply with India's EV adoption and skilled-technician shortage.",
      [("EV Powertrain & Battery Systems", "critical"), ("Electrical Diagnostics", "critical"),
       ("Motor & Controller Repair", "important"), ("Charging Infrastructure", "important"),
       ("Safety (high-voltage)", "critical")],
      ["ITI/diploma + EV-specific upskilling (OEM/ASDC courses)",
       "Train at EV OEM/dealer workshops",
       "Move into supervisory roles or own a workshop"],
      ["ITI/Diploma in automobile/electrical",
       "EV technician certification (ASDC / OEM programmes)"],
      ["ev", "automotive", "technician", "green-jobs", "emerging-tech"],
      ["Workshop", "Hands-on", "Technical"], "Growing fast - EV adoption and skills gap"),

    C("food_content_creator_in", "Food Blogger / Culinary Content Creator", "Media & Broadcasting", "no",
      15000, 400000, "Hobby to full-time creator with brand deals",
      "Create food and recipe content - reels, videos, blogs and reviews - monetised via brand deals, ads, restaurant promotions and events. A booming creator niche in India's food-obsessed social media.",
      [("Food Content Creation (video/photo)", "critical"), ("Recipe/Storytelling", "critical"),
       ("Editing & Reels", "important"), ("Audience Growth & SEO", "important"),
       ("Brand Collaboration & Monetisation", "important")],
      ["Pick a niche (regional/street food/healthy) and post consistently",
       "Grow on Instagram/YouTube and engage your audience",
       "Monetise via brand deals, ads and events"],
      ["No formal degree - content quality and consistency",
       "Culinary or media background (optional)"],
      ["food", "content-creator", "social-media", "blogging", "self-employment"],
      ["Online / Remote", "Self-employed", "Creative"], "Growing fast - large food creator economy"),
]


def main():
    with open(PATH, encoding="utf-8") as f:
        existing = json.load(f)
    existing_ids = {c["id"] for c in existing}
    existing_titles = {c["title"].strip().lower() for c in existing}

    to_add = []
    for c in NEW:
        if c["id"] in existing_ids:
            print("SKIP (id exists):", c["id"]); continue
        if c["title"].strip().lower() in existing_titles:
            print("SKIP (title exists):", c["title"]); continue
        to_add.append(c)

    if not to_add:
        print("Nothing new to add.")
        return

    # Textual append: preserve existing bytes, insert before the final ']'.
    with open(PATH, encoding="utf-8") as f:
        text = f.read()
    idx = text.rstrip().rfind("]")
    head = text.rstrip()[:idx].rstrip()  # ends with the last entry's '}'
    chunks = []
    for c in to_add:
        dumped = json.dumps(c, ensure_ascii=False, indent=2)
        chunks.append("\n".join("  " + ln for ln in dumped.splitlines()))
    new_text = head + ",\n" + ",\n".join(chunks) + "\n]\n"

    # Validate before writing
    parsed = json.loads(new_text)
    assert len(parsed) == len(existing) + len(to_add), "count mismatch"

    with open(PATH, "w", encoding="utf-8") as f:
        f.write(new_text)
    print(f"Added {len(to_add)} careers. Total now {len(parsed)}.")


if __name__ == "__main__":
    main()
