# Copyright (c) 2025-2026 K.N.Narin. Non-commercial use only. See LICENSE.
"""Batch 4: medical specialties, traditional Indian crafts, more engineering/tech,
sports, service, digital. Append-only, deduped. ASCII-only. Run from repo root."""
import json, os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PATH = os.path.join(HERE, "backend", "data", "careers.json")


def C(cid, title, category, collar, smin, smax, note, desc, skills, paths, quals, tags, work, growth):
    return {"id": cid, "title": title, "category": category, "region": "IN", "description": desc,
            "salary_range": {"min": smin, "max": smax, "currency": "INR/month", "note": note},
            "growth_outlook": growth, "work_style": work,
            "required_skills": [{"skill": s, "level": l} for s, l in skills],
            "entry_paths": paths, "qualifications": quals, "tags": tags, "collar": collar}


def S(*p): return list(p)

# helper for the common "MBBS + MD/DM specialist" shape
def DOC(cid, title, desc, core_skills, pg, tags):
    return C(cid, title, "Healthcare", "white", 70000, 800000,
             "Resident to senior consultant; private practice varies widely",
             desc,
             S(("Clinical Diagnosis","critical"), (core_skills[0],"critical"), (core_skills[1],"important"),
               ("Patient Management","important"), ("Medical Ethics","important")),
             ["MBBS + " + pg, "Residency and council registration", "Hospital consultant or private practice"],
             ["MBBS + " + pg, "NMC registration"],
             tags, ["Hospital/Clinic","Knowledge work","High-responsibility"], "Strong - specialist demand")


NEW = [
    # ----- Medical specialties -----
    DOC("cardiologist_in", "Cardiologist", "Diagnose and treat heart and blood-vessel conditions - from check-ups to interventions and cardiac care.",
        ["Cardiology","ECG/Echo Interpretation"], "MD + DM (Cardiology)", ["cardiologist","heart","doctor","specialist"]),
    DOC("dermatologist_in", "Dermatologist", "Treat skin, hair and nail conditions, and provide cosmetic dermatology - a high-demand, lifestyle-friendly specialty.",
        ["Dermatology","Skin Procedures"], "MD (Dermatology)", ["dermatologist","skin","doctor","specialist"]),
    DOC("psychiatrist_in", "Psychiatrist", "Diagnose and treat mental-health conditions with therapy and medication - a fast-growing field as awareness rises.",
        ["Psychiatry","Psychopharmacology"], "MD (Psychiatry)", ["psychiatrist","mental-health","doctor","specialist"]),
    DOC("radiologist_in", "Radiologist", "Interpret medical images (X-ray, CT, MRI, ultrasound) to diagnose disease and guide treatment.",
        ["Radiology & Imaging","Image Interpretation"], "MD (Radiology)", ["radiologist","imaging","doctor","specialist"]),
    DOC("gynecologist_in", "Gynaecologist / Obstetrician", "Care for women's reproductive health, pregnancy and childbirth - one of the most in-demand specialties.",
        ["Obstetrics & Gynaecology","Surgical/Delivery Skills"], "MS/MD (OBG)", ["gynaecologist","obstetrics","doctor","specialist"]),
    DOC("orthopedic_in", "Orthopaedic Surgeon", "Treat bones, joints, muscles and the spine - fractures, replacements and sports injuries.",
        ["Orthopaedics","Orthopaedic Surgery"], "MS (Orthopaedics)", ["orthopaedic","bones","surgeon","specialist"]),
    DOC("ophthalmologist_in", "Ophthalmologist (Eye Surgeon)", "Diagnose and treat eye diseases and perform eye surgery such as cataract and LASIK.",
        ["Ophthalmology","Eye Surgery"], "MS (Ophthalmology)", ["ophthalmologist","eye","surgeon","specialist"]),
    DOC("ent_in", "ENT Specialist (Otolaryngologist)", "Treat ear, nose and throat conditions, including surgery and hearing/balance disorders.",
        ["ENT (Otolaryngology)","ENT Surgery"], "MS (ENT)", ["ent","otolaryngology","surgeon","specialist"]),
    C("clinical_psychologist_in", "Clinical Psychologist", "Mental Health & Therapy", "white", 30000, 200000,
      "Practitioner to senior clinician/consultant",
      "Assess and treat mental-health and behavioural issues with psychotherapy and psychological testing.",
      S(("Clinical Assessment","critical"),("Psychotherapy","critical"),("Psychological Testing","important"),
        ("Empathy & Rapport","important"),("Case Documentation","helpful")),
      ["M.A/M.Sc Psychology + M.Phil Clinical Psychology (RCI)","RCI registration","Hospital/clinic/private practice"],
      ["M.Phil/PsyD Clinical Psychology; RCI registration"],
      ["psychology","mental-health","therapy","clinical"], ["Clinic / Online","Knowledge work"], "Growing fast - mental-health awareness"),
    C("counsellor_in", "Counsellor / Psychotherapist", "Mental Health & Therapy", "no", 20000, 150000,
      "Counsellor to own practice",
      "Support people through emotional, relationship, career and life challenges with talk-based counselling.",
      S(("Counselling Skills","critical"),("Active Listening & Empathy","critical"),("Therapeutic Techniques","important"),
        ("Ethics & Boundaries","important"),("Online Practice","helpful")),
      ["Psychology degree + counselling certification/PG diploma","Clinic/NGO/school/online roles","Own counselling practice"],
      ["Psychology degree; counselling diploma/certification"],
      ["counselling","mental-health","therapy","wellness"], ["Clinic / Online","Self-employed option"], "Growing fast"),
    C("speech_therapist_in", "Speech & Language Therapist", "Healthcare", "white", 20000, 120000,
      "Therapist to senior/clinic owner",
      "Diagnose and treat speech, language, communication and swallowing disorders in children and adults.",
      S(("Speech-Language Pathology","critical"),("Assessment & Therapy Plans","critical"),("Patience & Empathy","important"),
        ("Parent/Carer Guidance","important")),
      ["BASLP degree","RCI registration","Hospital/clinic/school or own practice"],
      ["BASLP (Audiology & Speech-Language Pathology); RCI registration"],
      ["speech-therapy","healthcare","rehab","communication"], ["Clinic","Hands-on"], "Growing - early-intervention demand"),
    C("homeopathy_doctor_in", "Homeopathy Doctor (BHMS)", "Healthcare", "white", 20000, 150000,
      "New graduate to established practice",
      "Diagnose and treat patients using homeopathic medicine - a recognised AYUSH system with wide patient demand in India.",
      S(("Homeopathic Materia Medica","critical"),("Case Taking & Diagnosis","critical"),("Patient Counselling","important"),
        ("Clinical Knowledge","important")),
      ["BHMS degree + internship","Register with Homeopathy Council","Clinic/practice or AYUSH roles"],
      ["BHMS degree","Homeopathy/AYUSH council registration"],
      ["homeopathy","ayush","doctor","healthcare"], ["Clinic","Knowledge work","Self-employed option"], "Stable - AYUSH demand"),

    # ----- Traditional Indian crafts & rural livelihoods -----
    C("potter_in", "Potter / Ceramic Artisan (Kumhar)", "Arts & Crafts", "blue", 10000, 60000,
      "Artisan to studio-pottery entrepreneur",
      "Shape clay into pots, diyas, planters, tableware and art on the wheel - a heritage craft with festive and studio-pottery demand.",
      S(("Wheel Throwing & Hand-building","critical"),("Glazing & Firing","important"),("Clay Preparation","important"),
        ("Design Variety","important"),("Selling/Marketing","helpful")),
      ["Family craft or pottery training","Sell at melas, festivals, studios","Studio pottery brand / workshops"],
      ["No formal degree - apprenticeship; ceramics course optional"],
      ["pottery","ceramics","handicraft","heritage-craft"], ["Workshop","Hands-on","Self-employed option"], "Stable - festive & studio-pottery revival"),
    C("blacksmith_in", "Blacksmith / Metal Forger (Lohar)", "Arts & Crafts", "blue", 12000, 60000,
      "Artisan to fabrication/decor business",
      "Forge and shape iron and steel into tools, gates, grills and decorative metalwork - a traditional trade with modern decor demand.",
      S(("Forging & Metal Shaping","critical"),("Tool Making","important"),("Welding/Fabrication","important"),
        ("Design","helpful"),("Safety","important")),
      ["Family craft or apprenticeship","Tools/fabrication/decor jobs","Decorative metal-art business"],
      ["No formal degree - apprenticeship"],
      ["blacksmith","metalwork","handicraft","trades"], ["Workshop","Physical","Self-employed option"], "Stable - decor & custom metalwork"),
    C("bamboo_craftsman_in", "Bamboo & Cane Craftsman", "Arts & Crafts", "blue", 10000, 50000,
      "Artisan to eco-craft entrepreneur",
      "Weave bamboo and cane into furniture, baskets, decor and eco-products - a sustainable craft with rising green-product demand.",
      S(("Bamboo/Cane Weaving","critical"),("Furniture/Product Making","important"),("Design","important"),
        ("Finishing","important"),("Selling","helpful")),
      ["Community craft or NER/handicraft training","Sell via melas, eco-stores, online","Eco-craft brand"],
      ["No formal degree - apprenticeship; handicraft training"],
      ["bamboo","cane","handicraft","eco-friendly"], ["Workshop","Hands-on","Self-employed option"], "Growing - eco-products demand"),
    C("woodcarver_in", "Woodcarver / Wood Artisan", "Arts & Crafts", "blue", 12000, 80000,
      "Artisan to custom furniture/art business",
      "Carve and craft wood into furniture, doors, idols and decorative art - skilled heritage work (Saharanpur, Channapatna, etc.).",
      S(("Wood Carving","critical"),("Joinery & Finishing","important"),("Design & Pattern","important"),
        ("Tool Mastery","important"),("Selling","helpful")),
      ["Apprentice in a woodcraft cluster","Custom/export furniture & art jobs","Own workshop / brand"],
      ["No formal degree - apprenticeship"],
      ["woodcarving","woodwork","handicraft","heritage-craft"], ["Workshop","Hands-on","Self-employed option"], "Stable - decor & export demand"),
    C("stone_sculptor_in", "Stone Sculptor / Shilpi", "Arts & Crafts", "blue", 12000, 100000,
      "Artisan to commissioned sculptor",
      "Carve stone into idols, statues, temple work and architectural elements - a revered heritage craft (Mahabalipuram, Rajasthan).",
      S(("Stone Carving","critical"),("Sculptural Design","important"),("Iconography/Proportions","important"),
        ("Tool & Material Knowledge","important")),
      ["Apprentice under a master sculptor (sthapati tradition)","Temple/commission work","Independent commissions"],
      ["No formal degree - traditional apprenticeship; fine-arts optional"],
      ["sculpture","stone-carving","handicraft","heritage"], ["Workshop","Physical","Self-employed option"], "Stable - temples & commissions"),
    C("idol_maker_in", "Idol Maker / Murti Artisan", "Arts & Crafts", "no", 12000, 120000,
      "Artisan to festive-idol business",
      "Sculpt and paint idols (Ganesh, Durga, etc.) in clay, plaster or eco-materials for festivals - highly seasonal, high-demand work.",
      S(("Idol Sculpting & Moulding","critical"),("Painting & Detailing","important"),("Eco-material Knowledge","important"),
        ("Seasonal Production Planning","important")),
      ["Family craft or apprenticeship in idol clusters","Seasonal festival production & sales","Workshop/brand for eco-idols"],
      ["No formal degree - apprenticeship"],
      ["idol-making","murti","handicraft","festive"], ["Workshop","Creative","Seasonal"], "Stable - festival demand; eco shift"),
    C("halwai_in", "Halwai / Sweet Maker", "Food & Hospitality", "no", 12000, 150000,
      "Sweet maker to mithai-shop owner",
      "Make traditional Indian sweets and snacks (mithai, namkeen) for shops, festivals and catering - a strong small-business path.",
      S(("Sweet & Snack Making","critical"),("Recipe & Quality Consistency","critical"),("Hygiene & Food Safety","important"),
        ("Costing & Selling","important")),
      ["Learn under an experienced halwai","Shop/catering work","Own mithai shop / festive supply"],
      ["No formal degree - apprenticeship; FSSAI licence for a shop"],
      ["sweets","mithai","food","self-employment"], ["Kitchen/Shop","Hands-on","Self-employed option"], "Stable - festive & daily demand"),
    C("papad_pickle_in", "Papad / Pickle Home-Food Entrepreneur", "Entrepreneurship & MSME", "no", 10000, 150000,
      "Home producer to packaged-food brand",
      "Make and sell papad, pickles, masalas and home-foods - a classic low-capital women-led MSME with growing D2C reach.",
      S(("Traditional Food Production","critical"),("Hygiene & Shelf-life","critical"),("Packaging & Branding","important"),
        ("Marketing/D2C","important"),("Costing","helpful")),
      ["Start from home kitchen; get FSSAI registration","Sell locally, then via stores/online","Build a packaged brand / SHG"],
      ["No degree; FSSAI registration; MSME/Udyam for growth"],
      ["food","papad","pickle","msme","self-employment"], ["Home-based","Self-employed","Entrepreneurial"], "Growing - D2C home foods"),
    C("shepherd_goat_in", "Goat / Sheep Farmer (Pashupalak)", "Agriculture & Farming", "no", 12000, 120000,
      "Smallholder to commercial goat/sheep farm",
      "Rear goats or sheep for meat, milk and wool - a low-input, high-return rural livestock business with strong meat demand.",
      S(("Livestock Rearing","critical"),("Animal Health & Breeding","important"),("Grazing/Feed Management","important"),
        ("Marketing","important")),
      ["Livestock training (KVK/animal husbandry dept)","Start with a small flock","Scale to commercial farming"],
      ["Animal husbandry training; no degree required"],
      ["goat-farming","livestock","agriculture","agripreneur"], ["Farm/Field","Outdoor","Self-employed"], "Good - meat demand"),
    C("fisherman_aqua_in", "Fish Farmer / Aquaculture Entrepreneur", "Agriculture & Farming", "no", 12000, 150000,
      "Smallholder to commercial aquaculture",
      "Breed and raise fish or shrimp in ponds/tanks for sale - a high-value agribusiness backed by fisheries (Blue Revolution) schemes.",
      S(("Fish/Shrimp Rearing","critical"),("Water Quality Management","critical"),("Feed & Disease Management","important"),
        ("Marketing & Supply","important")),
      ["Fisheries training (KVK/fisheries dept)","Start a pond/tank unit","Scale to commercial aquaculture"],
      ["Fisheries training; no degree required"],
      ["aquaculture","fish-farming","agriculture","agripreneur"], ["Farm/Pond","Self-employed","Entrepreneurial"], "Growing - Blue Revolution"),

    # ----- Engineering / tech (more) -----
    C("instrumentation_engineer_in", "Instrumentation & Control Engineer", "Manufacturing & Production", "white", 28000, 200000,
      "Graduate engineer to senior/control lead",
      "Design and maintain instruments and control systems that measure and automate industrial processes (oil, power, pharma).",
      S(("Instrumentation & Control","critical"),("PLC/SCADA","important"),("Process Measurement","important"),
        ("Electronics","important"),("Calibration","helpful")),
      ["B.E Instrumentation/Electronics","Process-industry roles","Specialise (automation/control)"],
      ["B.E/B.Tech in Instrumentation/Control Engineering"],
      ["instrumentation","control","automation","engineering"], ["Plant/Office","Technical"], "Stable"),
    C("iot_engineer_in", "IoT Engineer", "Technology", "white", 35000, 250000,
      "Engineer to IoT solutions lead",
      "Build connected-device systems - sensors, embedded firmware, connectivity and cloud dashboards - for smart homes, industry and cities.",
      S(("Embedded & Firmware","critical"),("Sensors & Connectivity (MQTT/BLE)","critical"),("Cloud/IoT Platforms","important"),
        ("Programming (C/Python)","important"),("Data Handling","helpful")),
      ["ECE/CS background + IoT projects","IoT/embedded roles","Solutions architecture"],
      ["B.E/B.Tech (ECE/CS); IoT project portfolio"],
      ["iot","embedded","emerging-tech","engineering"], ["Office/Lab","Technical"], "Growing - smart devices"),
    C("frontend_developer_in", "Front-end Developer", "Technology", "white", 30000, 250000,
      "Junior to senior/lead front-end engineer",
      "Build the user-facing part of websites and apps - responsive, accessible interfaces with modern frameworks.",
      S(("HTML/CSS/JavaScript","critical"),("React/Vue/Angular","critical"),("Responsive & Accessible UI","important"),
        ("APIs & State Management","important"),("Testing","helpful")),
      ["Learn web dev + build projects","Front-end roles","Specialise/lead or go full-stack"],
      ["Any degree or self-taught; portfolio matters most"],
      ["frontend","web","javascript","react"], ["Office / Remote","Team-based"], "Strong"),
    C("backend_developer_in", "Back-end Developer", "Technology", "white", 35000, 300000,
      "Junior to senior/lead back-end engineer",
      "Build the server-side logic, APIs and databases that power applications - performance, security and scalability.",
      S(("Server-side Language (Node/Python/Java)","critical"),("Databases & SQL","critical"),("API Design","important"),
        ("Auth & Security","important"),("Cloud Basics","helpful")),
      ["Learn backend + build APIs/projects","Back-end roles","Specialise/architect or full-stack"],
      ["Any degree or self-taught; portfolio matters most"],
      ["backend","api","web","software"], ["Office / Remote","Team-based"], "Strong"),

    # ----- Sports / fitness -----
    C("footballer_in", "Professional Footballer", "Sports & Athletics", "no", 20000, 500000,
      "Academy/club player to pro league; varies hugely",
      "Play football professionally for clubs and country, training intensively - growing in India with ISL and academies.",
      S(("Football Skill & Tactics","critical"),("Fitness & Stamina","critical"),("Teamwork","important"),
        ("Discipline","important"),("Mental Toughness","important")),
      ["Train at academies from a young age","Trials and club contracts","Pro leagues / coaching later"],
      ["No degree - talent, training and trials"],
      ["football","sports","athlete","fitness"], ["Field","Physical","Performance-based"], "Growing - ISL & academies"),
    C("athlete_track_in", "Athlete (Track & Field)", "Sports & Athletics", "no", 15000, 300000,
      "Trainee to national/international athlete",
      "Compete in running, jumping or throwing events at state, national and international level, with intense training.",
      S(("Event-specific Technique","critical"),("Strength & Conditioning","critical"),("Discipline & Diet","important"),
        ("Mental Focus","important")),
      ["Train under a coach; compete at school/state","SAI/national camps & competitions","Pro/govt-job-via-sports quota"],
      ["No degree - talent and training; sports quota jobs possible"],
      ["athletics","sports","athlete","fitness"], ["Track/Field","Physical","Performance-based"], "Stable - govt support & quotas"),
    C("wrestler_in", "Wrestler / Pehlwan (Professional)", "Sports & Athletics", "no", 15000, 300000,
      "Akhada trainee to national/Olympic wrestler",
      "Compete in wrestling (kushti/freestyle) at akhadas, nationals and internationals - a deep-rooted Indian sport with Olympic glory.",
      S(("Wrestling Technique","critical"),("Strength & Stamina","critical"),("Diet & Discipline","critical"),
        ("Mental Toughness","important")),
      ["Train at an akhada/academy","State & national competitions","International/Olympic path; sports-quota jobs"],
      ["No degree - training and competition record"],
      ["wrestling","kushti","sports","athlete"], ["Akhada/Mat","Physical","Performance-based"], "Stable - strong tradition & quotas"),
    C("cricket_umpire_in", "Cricket Umpire / Referee", "Sports & Athletics", "no", 15000, 200000,
      "Local umpire to elite-panel official",
      "Officiate cricket matches - applying the laws, making decisions and managing the game at club to international level.",
      S(("Laws of Cricket","critical"),("Decision-making & Focus","critical"),("Match Management","important"),
        ("Fitness","helpful")),
      ["Pass state/BCCI umpiring exams","Officiate club/state matches","Rise to national/elite panels"],
      ["Umpiring certification (state assoc/BCCI)"],
      ["umpire","cricket","sports","officiating"], ["Field","Focus-intensive"], "Stable - cricket's scale"),
    C("sports_physio_in", "Sports Physiotherapist", "Sports & Athletics", "white", 25000, 180000,
      "Physio to team/elite sports physio",
      "Prevent, assess and rehabilitate athletes' injuries and optimise performance with sport-specific physiotherapy.",
      S(("Sports Injury Rehab","critical"),("Anatomy & Biomechanics","critical"),("Manual Therapy","important"),
        ("Strength & Conditioning","important"),("Athlete Communication","helpful")),
      ["BPT + sports physio specialisation","Clinic/academy/team roles","Elite-team physio"],
      ["BPT + sports physiotherapy training; council registration"],
      ["sports-physio","physiotherapy","sports","rehab"], ["Clinic/Field","Hands-on"], "Growing - sports investment"),

    # ----- Service / everyday -----
    C("waiter_steward_in", "Waiter / Restaurant Steward", "Food & Hospitality", "pink", 12000, 45000,
      "Steward to captain/F&B supervisor",
      "Serve food and drink and look after guests in restaurants and hotels - the front line of hospitality service.",
      S(("Food & Beverage Service","critical"),("Customer Service","critical"),("Menu Knowledge","important"),
        ("Hygiene & Etiquette","important")),
      ["On-the-job or hotel-management certificate","Restaurant/hotel roles","Captain/supervisor/F&B"],
      ["No degree; F&B/hotel-management certificate helps"],
      ["waiter","hospitality","service","f&b"], ["Restaurant/Hotel","Customer-facing"], "Stable"),
    C("gardener_landscaper_in", "Gardener / Landscaper (Mali)", "Everyday Work & Trades", "no", 12000, 70000,
      "Gardener to landscaping business owner",
      "Plant and maintain gardens, lawns and green spaces for homes, societies and businesses - and design landscapes.",
      S(("Plant & Garden Care","critical"),("Landscaping & Design","important"),("Soil/Irrigation","important"),
        ("Tools & Maintenance","important")),
      ["Learn on the job or horticulture training","Garden-maintenance contracts","Landscaping business"],
      ["No degree; horticulture/landscaping course optional"],
      ["gardening","landscaping","horticulture","self-employment"], ["Outdoor","Physical","Self-employed option"], "Stable - urban green demand"),
    C("housekeeping_in", "Housekeeping Supervisor / Staff", "Food & Hospitality", "pink", 12000, 55000,
      "Attendant to housekeeping supervisor/executive",
      "Maintain cleanliness, hygiene and presentation in hotels, hospitals and corporates - rooms, public areas and laundry.",
      S(("Cleaning & Hygiene Standards","critical"),("Attention to Detail","important"),("Team Coordination","important"),
        ("Inventory/Supplies","helpful")),
      ["On-the-job training","Hotel/hospital/facility roles","Supervisor/executive housekeeper"],
      ["No degree; hotel-management certificate helps for supervisory roles"],
      ["housekeeping","hospitality","facilities","service"], ["Hotel/Facility","Physical","Service"], "Stable"),

    # ----- Digital / modern -----
    C("youtuber_in", "YouTuber / Video Content Creator", "Media & Broadcasting", "no", 10000, 1000000,
      "Hobbyist to full-time creator with brand deals",
      "Create videos for YouTube/social platforms in a niche, building an audience and monetising via ads, sponsorships and products.",
      S(("Video Creation & Editing","critical"),("Niche Content & Storytelling","critical"),("Audience Growth & SEO","important"),
        ("On-camera/Presentation","important"),("Monetisation & Brand Deals","important")),
      ["Pick a niche and publish consistently","Grow audience and engagement","Monetise via ads/sponsors/products"],
      ["No degree - skill, consistency and creativity"],
      ["youtube","content-creator","video","social-media"], ["Online / Remote","Self-employed","Creative"], "Growing fast - creator economy"),
    C("virtual_assistant_in", "Virtual Assistant", "Business & Management", "no", 15000, 120000,
      "VA to VA-agency owner",
      "Provide remote admin, scheduling, email, research and support to businesses and entrepreneurs worldwide.",
      S(("Organisation & Admin","critical"),("Communication (written)","critical"),("Tools (Calendar/Docs/CRM)","important"),
        ("Time Management","important"),("Discretion","helpful")),
      ["Build admin/communication skills","Freelance platforms or direct clients","Specialise or run a VA agency"],
      ["No degree; reliability and communication matter"],
      ["virtual-assistant","remote","admin","freelance"], ["Online / Remote","Self-employed option"], "Growing - remote work"),
    C("seo_specialist_in", "SEO Specialist", "Marketing & Sales", "white", 20000, 180000,
      "Executive to SEO/organic-growth lead",
      "Improve websites' search rankings and organic traffic through content, technical SEO and link strategy.",
      S(("SEO (on-page/technical/off-page)","critical"),("Keyword & Content Strategy","critical"),("Analytics (GA/Search Console)","important"),
        ("Basic HTML","important"),("Copywriting","helpful")),
      ["Learn SEO + practise on a site","Agency/in-house roles","Grow to organic-growth lead/consultant"],
      ["No fixed degree; results and portfolio matter"],
      ["seo","digital-marketing","content","growth"], ["Office / Remote","Knowledge work"], "Strong - digital marketing"),
    C("community_manager_in", "Community Manager", "Marketing & Sales", "white", 20000, 150000,
      "Associate to community/growth lead",
      "Build and nurture online communities (Discord, social, forums) for brands and products - engagement, moderation and growth.",
      S(("Community Building & Moderation","critical"),("Communication","critical"),("Content & Events","important"),
        ("Analytics","important"),("Empathy","helpful")),
      ["Run/grow a community or volunteer","Brand/product community roles","Grow to community/growth lead"],
      ["No fixed degree; community track record matters"],
      ["community","social-media","marketing","engagement"], ["Online / Remote","People-facing"], "Growing - community-led growth"),
]


def main():
    with open(PATH, encoding="utf-8") as f:
        existing = json.load(f)
    ids = {c["id"] for c in existing}
    titles = {c["title"].strip().lower() for c in existing}
    to_add = []
    for c in NEW:
        if c["id"] in ids or c["title"].strip().lower() in titles:
            print("SKIP:", c["id"]); continue
        ids.add(c["id"]); titles.add(c["title"].strip().lower()); to_add.append(c)
    if not to_add:
        print("Nothing new."); return
    with open(PATH, encoding="utf-8") as f:
        text = f.read()
    idx = text.rstrip().rfind("]")
    head = text.rstrip()[:idx].rstrip()
    chunks = ["\n".join("  " + ln for ln in json.dumps(c, ensure_ascii=False, indent=2).splitlines()) for c in to_add]
    new_text = head + ",\n" + ",\n".join(chunks) + "\n]\n"
    parsed = json.loads(new_text)
    assert len(parsed) == len(existing) + len(to_add)
    with open(PATH, "w", encoding="utf-8") as f:
        f.write(new_text)
    print(f"Added {len(to_add)}. Total now {len(parsed)}.")


if __name__ == "__main__":
    main()
