# Copyright (c) 2025-2026 K.N.Narin. Non-commercial use only. See LICENSE.
"""Batch 3: engineering, sciences, creative/media, trades, agriculture, finance,
and modern roles. Append-only, deduped. ASCII-only. Run from repo root."""
import json, os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PATH = os.path.join(HERE, "backend", "data", "careers.json")


def C(cid, title, category, collar, smin, smax, note, desc, skills, paths, quals, tags, work, growth):
    return {"id": cid, "title": title, "category": category, "region": "IN", "description": desc,
            "salary_range": {"min": smin, "max": smax, "currency": "INR/month", "note": note},
            "growth_outlook": growth, "work_style": work,
            "required_skills": [{"skill": s, "level": l} for s, l in skills],
            "entry_paths": paths, "qualifications": quals, "tags": tags, "collar": collar}


def S(*p): return list(p)


NEW = [
    # ----- Engineering disciplines -----
    C("mechanical_engineer_in", "Mechanical Engineer", "Manufacturing & Production", "white", 25000, 180000,
      "Graduate engineer to senior/lead engineer",
      "Design, develop and maintain mechanical systems and machines - from automobiles to HVAC to manufacturing plants.",
      S(("Mechanical Design & CAD","critical"),("Thermodynamics & Mechanics","critical"),("Manufacturing Processes","important"),
        ("Problem-solving","important"),("Project Management","helpful")),
      ["B.E/B.Tech Mechanical or diploma","Campus/entry roles in mfg/auto/energy","Specialise and grow to lead"],
      ["Diploma/B.E/B.Tech in Mechanical Engineering"],
      ["mechanical","engineering","manufacturing","design"], ["Office/Plant","Technical"], "Stable"),
    C("electrical_engineer_in", "Electrical Engineer", "Energy & Utilities", "white", 25000, 180000,
      "Graduate engineer to senior engineer",
      "Design and manage electrical systems - power generation, distribution, machines and control - across industries and utilities.",
      S(("Electrical Systems & Circuits","critical"),("Power Distribution","important"),("Control Systems","important"),
        ("Electrical Safety/Codes","important"),("CAD/Schematics","helpful")),
      ["Diploma/B.E Electrical","Utility/industry/construction roles","Specialise (power/control)"],
      ["Diploma/B.E/B.Tech in Electrical Engineering"],
      ["electrical","engineering","power","energy"], ["Office/Site/Plant","Technical"], "Stable"),
    C("electronics_engineer_in", "Electronics & Communication Engineer", "Technology", "white", 25000, 180000,
      "Graduate engineer to design/lead engineer",
      "Design electronic circuits, embedded systems and communication equipment - from chips to telecom to consumer electronics.",
      S(("Electronics & Circuit Design","critical"),("Embedded Systems","important"),("Signal/Communication Systems","important"),
        ("PCB Design","important"),("Microcontrollers","helpful")),
      ["B.E/B.Tech ECE or diploma","Electronics/telecom/embedded roles","Specialise (VLSI/embedded/telecom)"],
      ["Diploma/B.E/B.Tech in Electronics & Communication"],
      ["electronics","engineering","embedded","telecom"], ["Office/Lab","Technical"], "Good"),
    C("civil_structural_engineer_in", "Structural Engineer", "Architecture & Urban Planning", "white", 28000, 200000,
      "Graduate engineer to senior structural engineer",
      "Design safe, stable structures - buildings, bridges, towers - calculating loads, materials and resilience.",
      S(("Structural Analysis & Design","critical"),("Building Codes & Standards","critical"),("Structural Software (STAAD/ETABS)","important"),
        ("Materials Knowledge","important"),("Site Coordination","helpful")),
      ["B.E Civil + structural specialisation/M.Tech","Consultancy/construction roles","Senior/independent design"],
      ["B.E/B.Tech Civil; M.Tech Structural valued"],
      ["structural","civil","engineering","construction"], ["Office/Site","Technical"], "Good - infrastructure"),
    C("chemical_engineer_in", "Chemical Engineer", "Manufacturing & Production", "white", 28000, 200000,
      "Graduate engineer to plant/process lead",
      "Design and run chemical processes and plants - converting raw materials into products in petrochemicals, pharma, FMCG and more.",
      S(("Chemical Process Design","critical"),("Process Safety","critical"),("Mass & Heat Transfer","important"),
        ("Plant Operations","important"),("Quality Control","helpful")),
      ["B.E/B.Tech Chemical","Process/plant roles in chemicals/pharma/oil","Specialise and lead"],
      ["B.E/B.Tech in Chemical Engineering"],
      ["chemical","engineering","process","manufacturing"], ["Plant/Office","Technical"], "Stable"),
    C("biomedical_engineer_in", "Biomedical Engineer", "Healthcare", "white", 25000, 150000,
      "Graduate engineer to senior/clinical engineer",
      "Design and maintain medical devices and healthcare technology - imaging, implants, diagnostics - bridging engineering and medicine.",
      S(("Biomedical Instrumentation","critical"),("Medical Device Knowledge","important"),("Electronics","important"),
        ("Regulatory/Quality Standards","important"),("Maintenance & Calibration","helpful")),
      ["B.Tech Biomedical Engineering","Hospital/medical-device roles","Specialise (devices/clinical engineering)"],
      ["B.E/B.Tech in Biomedical Engineering"],
      ["biomedical","engineering","healthcare","devices"], ["Hospital/Industry","Technical"], "Growing - medtech"),
    C("industrial_engineer_in", "Industrial / Production Engineer", "Manufacturing & Production", "white", 25000, 160000,
      "Graduate engineer to operations/plant manager",
      "Optimise manufacturing and operations - efficiency, quality, layout, supply and lean processes - to cut waste and cost.",
      S(("Process Optimisation & Lean","critical"),("Production Planning","important"),("Quality Systems","important"),
        ("Data Analysis","important"),("Operations Management","helpful")),
      ["B.E Industrial/Production/Mechanical","Manufacturing operations roles","Grow to plant/ops management"],
      ["B.E/B.Tech in Industrial/Production Engineering"],
      ["industrial-engineering","manufacturing","operations","lean"], ["Plant/Office","Technical"], "Good"),
    C("robotics_engineer_in", "Robotics Engineer", "Technology", "white", 35000, 300000,
      "Graduate engineer to robotics lead",
      "Design, build and program robots and automation systems for manufacturing, logistics, healthcare and research.",
      S(("Robotics & Control","critical"),("Programming (C++/Python/ROS)","critical"),("Mechatronics","important"),
        ("Sensors & Actuators","important"),("Computer Vision","helpful")),
      ["Engineering (mech/ECE/CS) + robotics projects","Automation/robotics firms or R&D","Specialise and lead"],
      ["B.E/B.Tech + robotics specialisation/projects"],
      ["robotics","automation","engineering","emerging-tech"], ["Lab/Plant","Technical","High-skill"], "Growing fast - automation"),
    C("marine_engineer_in", "Marine Engineer", "Maritime & Shipping", "white", 40000, 400000,
      "Cadet to chief engineer",
      "Operate and maintain ship engines and machinery aboard merchant vessels - a well-paid global seafaring career.",
      S(("Marine Engineering Systems","critical"),("Engine Maintenance","critical"),("Safety at Sea","critical"),
        ("Troubleshooting","important"),("Watchkeeping","important")),
      ["Marine Engineering degree (DG Shipping approved)","Sail as cadet/junior engineer","Rise to chief engineer"],
      ["B.E Marine Engineering (DG Shipping approved); CoC certifications"],
      ["marine","shipping","engineering","seafaring"], ["Ship/Sea","Contract voyages","High-pay"], "Good - global shipping"),
    C("mining_engineer_in", "Mining Engineer", "Energy & Utilities", "white", 35000, 250000,
      "Graduate engineer to mine manager",
      "Plan and oversee safe, efficient extraction of minerals and coal - mine design, operations and safety.",
      S(("Mine Planning & Operations","critical"),("Mining Safety","critical"),("Geology basics","important"),
        ("Equipment & Blasting","important")),
      ["B.Tech Mining Engineering","Mine site roles","Statutory certs, rise to manager"],
      ["B.E/B.Tech in Mining Engineering; statutory certificates"],
      ["mining","engineering","minerals","energy"], ["Mine/Field","Physical","Technical"], "Stable"),

    # ----- Sciences / research -----
    C("research_scientist_in", "Research Scientist", "Science & Research", "white", 35000, 250000,
      "Junior researcher to principal scientist",
      "Conduct scientific research to advance knowledge or develop products - experiments, analysis and publishing in academia or R&D labs.",
      S(("Research Methodology","critical"),("Domain Expertise","critical"),("Data Analysis & Statistics","important"),
        ("Scientific Writing","important"),("Lab/Experimental Skills","important")),
      ["M.Sc/PhD in the field","Research/PhD roles in labs/institutes","Build a publication record"],
      ["M.Sc/PhD in the relevant science"],
      ["research","science","r&d","academia"], ["Lab/Institute","Knowledge work"], "Stable"),
    C("statistician_in", "Statistician / Biostatistician", "Data & Analytics", "white", 35000, 250000,
      "Analyst to senior statistician",
      "Apply statistical methods to design studies and interpret data - in research, pharma, government, finance and analytics.",
      S(("Statistics & Probability","critical"),("Statistical Software (R/SAS/Python)","critical"),("Study/Experiment Design","important"),
        ("Data Interpretation","important"),("Communication of Results","helpful")),
      ["M.Sc Statistics or related","Analytics/pharma/research roles","Specialise (bio/econometrics)"],
      ["M.Sc Statistics / strong quantitative degree"],
      ["statistics","data","analytics","research"], ["Office / Remote","Knowledge work"], "Strong - data demand"),
    C("microbiologist_in", "Microbiologist", "Science & Research", "white", 20000, 120000,
      "Lab scientist to senior microbiologist",
      "Study microorganisms for healthcare, food, pharma and environment - testing, quality control and research.",
      S(("Microbiology Techniques","critical"),("Lab & Sterile Practice","critical"),("Sample Analysis","important"),
        ("Quality Control","important"),("Documentation","helpful")),
      ["B.Sc/M.Sc Microbiology","Lab/QC roles in pharma/food/diagnostics","Research or QA management"],
      ["B.Sc/M.Sc in Microbiology"],
      ["microbiology","science","lab","research"], ["Lab","Technical"], "Good"),
    C("environmental_scientist_in", "Environmental Scientist", "Science & Research", "white", 25000, 150000,
      "Analyst to senior environmental scientist",
      "Study and protect the environment - pollution, water, climate, impact assessments - for industry, govt and NGOs.",
      S(("Environmental Science","critical"),("Sampling & Lab Analysis","important"),("EIA & Compliance","important"),
        ("Data Analysis","important"),("Report Writing","helpful")),
      ["B.Sc/M.Sc Environmental Science","Consultancy/industry/NGO/govt roles","Specialise (EIA/water/air)"],
      ["B.Sc/M.Sc in Environmental Science"],
      ["environment","science","sustainability","ecology"], ["Field/Lab/Office","Knowledge work"], "Growing - ESG & regulation"),
    C("geologist_in", "Geologist", "Energy & Utilities", "white", 28000, 200000,
      "Junior geologist to senior/exploration geologist",
      "Study the earth's structure and resources - for mining, oil and gas, groundwater, and natural-hazard assessment.",
      S(("Geology & Mineralogy","critical"),("Field Survey & Mapping","critical"),("GIS & Remote Sensing","important"),
        ("Sample Analysis","important")),
      ["M.Sc Geology","Mining/oil/groundwater/survey roles","Specialise (exploration/hydro)"],
      ["M.Sc in Geology / Applied Geology"],
      ["geology","earth-science","mining","exploration"], ["Field/Lab","Technical"], "Stable"),

    # ----- Creative / media (more) -----
    C("makeup_artist_in", "Makeup Artist", "Beauty & Wellness", "no", 15000, 250000,
      "Freelancer to celebrity/bridal makeup artist",
      "Do makeup for weddings, fashion, film, TV and events - bridal, HD, special effects and editorial looks.",
      S(("Makeup Techniques (bridal/HD/SFX)","critical"),("Skin & Colour Knowledge","important"),("Hygiene","important"),
        ("Client Handling","important"),("Portfolio & Social Media","important")),
      ["Makeup course + assist a senior artist","Build a portfolio (weddings/shoots)","Freelance brand / studio tie-ups"],
      ["Professional makeup course; portfolio is key"],
      ["makeup","beauty","bridal","creative"], ["Studio/On-location","Creative","Self-employed option"], "Good - weddings & media"),
    C("hair_stylist_in", "Hair Stylist / Hairdresser", "Beauty & Wellness", "pink", 14000, 120000,
      "Stylist to salon owner",
      "Cut, colour, style and treat hair in salons or freelance - a steady, creative, in-person service everywhere.",
      S(("Hair Cutting & Styling","critical"),("Colouring & Treatments","important"),("Client Consultation","important"),
        ("Hygiene & Tools","important")),
      ["Hairdressing course or salon apprenticeship","Salon roles","Senior stylist or own salon"],
      ["Hairdressing/cosmetology course (optional)"],
      ["hair","beauty","salon","service"], ["Salon","Hands-on","Self-employed option"], "Stable"),
    C("illustrator_in", "Illustrator / Concept Artist", "Design & Creative", "no", 18000, 200000,
      "Freelancer to senior/lead artist",
      "Create illustrations and concept art for books, games, ads, animation and brands - across digital and traditional media.",
      S(("Drawing & Illustration","critical"),("Digital Art Tools (Photoshop/Procreate)","critical"),("Composition & Colour","important"),
        ("Concept Development","important"),("Client/Brief Work","helpful")),
      ["Build a strong portfolio","Freelance or studio (games/animation/publishing)","Specialise (concept/editorial)"],
      ["No fixed degree - portfolio is the credential; art education helps"],
      ["illustration","art","concept-art","creative"], ["Studio / Remote","Creative","Self-employed option"], "Good - games & content"),
    C("motion_graphics_in", "Motion Graphics Designer", "Design & Creative", "white", 25000, 180000,
      "Junior to senior/lead motion designer",
      "Create animated graphics and visual effects for ads, explainers, social media and broadcast.",
      S(("Motion Design (After Effects)","critical"),("Animation Principles","important"),("Design & Typography","important"),
        ("Video Editing","important"),("3D basics","helpful")),
      ["Learn After Effects + design","Build a reel","Agency/studio/in-house roles"],
      ["Any degree; strong reel matters most"],
      ["motion-graphics","animation","design","video"], ["Studio / Remote","Creative"], "Strong - video content"),
    C("radio_jockey_in", "Radio Jockey / Podcast Host", "Media & Broadcasting", "no", 18000, 200000,
      "RJ to popular host/creator",
      "Host radio shows or podcasts - talking, interviewing, entertaining and building an audience on air and online.",
      S(("On-air Presentation & Voice","critical"),("Spontaneity & Wit","important"),("Audio Production","important"),
        ("Audience Engagement","important"),("Content Planning","helpful")),
      ["Build a demo / start a podcast","RJ auditions or grow a show online","Brand deals and live events"],
      ["No fixed degree; mass-comm helps; demo matters"],
      ["radio","podcast","media","broadcasting"], ["Studio / Remote","Creative","Public-facing"], "Stable to growing - podcasting"),
    C("choreographer_in", "Choreographer / Dance Director", "Film & Entertainment", "no", 18000, 250000,
      "Assistant to lead choreographer",
      "Create and direct dance routines for films, stage, events and music videos, and train performers.",
      S(("Choreography & Dance","critical"),("Music & Rhythm","important"),("Teaching/Direction","important"),
        ("Creativity","important"),("Team Coordination","helpful")),
      ["Strong dance background","Assist established choreographers","Lead projects/own dance company"],
      ["No formal degree - skill and credits"],
      ["choreography","dance","film","creative"], ["Studio/Set","Creative","Physical"], "Good - film & events"),

    # ----- Trades / mechanics (more) -----
    C("cnc_machinist_in", "CNC Machinist / Operator", "Manufacturing & Production", "blue", 16000, 70000,
      "Operator to CNC programmer/supervisor",
      "Set up and run CNC machines to produce precision metal/plastic parts from engineering drawings.",
      S(("CNC Operation & Setup","critical"),("Blueprint Reading","critical"),("Measurement/Metrology","important"),
        ("CNC Programming (G-code)","important"),("Quality Inspection","helpful")),
      ["ITI (machinist/turner) + CNC training","Manufacturing shop-floor roles","Programmer/supervisor"],
      ["ITI (Machinist/Turner) + CNC training"],
      ["cnc","machining","manufacturing","trades"], ["Workshop","Technical","Hands-on"], "Good - manufacturing push"),
    C("diesel_mechanic_in", "Diesel / Heavy Vehicle Mechanic", "Automotive & EV", "blue", 16000, 70000,
      "Mechanic to workshop in-charge",
      "Service and repair trucks, buses and heavy diesel engines - keeping commercial and transport fleets running.",
      S(("Diesel Engine Repair","critical"),("Diagnostics","important"),("Hydraulics/Transmission","important"),
        ("Tools & Safety","important")),
      ["ITI (diesel mechanic)","Fleet/transport workshop roles","Workshop in-charge or own garage"],
      ["ITI (Mechanic Diesel)"],
      ["diesel","mechanic","automotive","trades"], ["Workshop","Hands-on","Physical"], "Stable"),
    C("mobile_repair_in", "Mobile / Electronics Repair Technician", "Everyday Work & Trades", "no", 12000, 70000,
      "Technician to repair-shop owner",
      "Diagnose and repair smartphones, laptops and electronics - hardware, software and component-level fixes.",
      S(("Mobile/Electronics Repair","critical"),("Component-level Diagnostics","important"),("Soldering","important"),
        ("Software/Flashing","important"),("Customer Service","helpful")),
      ["Mobile repair course or apprenticeship","Repair-shop roles","Own a repair shop"],
      ["Mobile repair course (optional); hands-on skill"],
      ["mobile-repair","electronics","trades","self-employment"], ["Shop","Hands-on","Self-employed option"], "Stable - huge device base"),
    C("barber_in", "Barber / Hairdresser (Men's)", "Beauty & Wellness", "pink", 12000, 80000,
      "Barber to salon owner",
      "Cut and style men's hair and beards, give grooming services - a steady neighbourhood and premium-salon trade.",
      S(("Haircutting & Beard Styling","critical"),("Grooming Services","important"),("Hygiene & Tools","important"),
        ("Customer Service","important")),
      ["Learn under an experienced barber","Salon roles","Own a salon/grooming lounge"],
      ["No formal degree - apprenticeship; grooming course optional"],
      ["barber","grooming","salon","service"], ["Salon","Hands-on","Self-employed option"], "Stable"),
    C("florist_in", "Florist / Flower Decorator", "Arts & Crafts", "no", 12000, 100000,
      "Shop assistant to floral-decor business owner",
      "Arrange flowers and design decor for weddings, events, gifts and shops - a creative, seasonal-demand business.",
      S(("Floral Arrangement & Design","critical"),("Event Decor","important"),("Sourcing & Freshness","important"),
        ("Customer Service","important")),
      ["Learn floristry on the job or via courses","Flower shop or event-decor work","Own shop / event florist"],
      ["No formal degree - skill and taste"],
      ["florist","flowers","decor","self-employment"], ["Shop/Events","Creative","Self-employed option"], "Stable - weddings & gifting"),

    # ----- Agriculture / rural (more) -----
    C("agronomist_in", "Agronomist / Agriculture Officer", "Agriculture & Farming", "white", 25000, 120000,
      "Field officer to agronomy lead",
      "Advise farmers and agri-businesses on crops, soil, irrigation and yield - improving productivity with science.",
      S(("Agronomy & Crop Science","critical"),("Soil & Nutrient Management","important"),("Pest/Disease Management","important"),
        ("Farmer Advisory","important"),("Data/Field Trials","helpful")),
      ["B.Sc/M.Sc Agriculture","Agri-input/agritech/govt extension roles","Specialise and lead"],
      ["B.Sc/M.Sc in Agriculture / Agronomy"],
      ["agronomy","agriculture","crop-science","advisory"], ["Field/Office","Knowledge work"], "Good - agritech"),
    C("poultry_farmer_in", "Poultry Farming Entrepreneur", "Agriculture & Farming", "no", 15000, 200000,
      "Small unit to commercial poultry business",
      "Raise chickens for eggs or meat - a high-demand, scalable agribusiness with broiler and layer models.",
      S(("Poultry Management","critical"),("Disease/Biosecurity","critical"),("Feed & Nutrition","important"),
        ("Marketing & Supply","important"),("Costing","helpful")),
      ["Poultry training (KVK/agri-university)","Start a small unit; tie up buyers/integrators","Scale to commercial"],
      ["Poultry farming training (KVK); no degree required"],
      ["poultry","farming","agriculture","agripreneur"], ["Farm","Self-employed","Entrepreneurial"], "Good - protein demand"),
    C("dairy_entrepreneur_in", "Dairy Farming Entrepreneur", "Agriculture & Farming", "no", 15000, 200000,
      "Smallholder to dairy business owner",
      "Raise dairy cattle and produce/sell milk and products, often through cooperatives or direct D2C.",
      S(("Dairy Cattle Management","critical"),("Animal Health & Breeding","important"),("Milk Quality & Handling","important"),
        ("Marketing/Cooperative tie-up","important"),("Costing","helpful")),
      ["Dairy training (KVK/NDDB)","Start with a few animals; join a cooperative","Scale and add value (products)"],
      ["Dairy farming training (KVK/NDDB); no degree required"],
      ["dairy","farming","agriculture","agripreneur"], ["Farm","Self-employed","Entrepreneurial"], "Stable - steady milk demand"),
    C("sericulture_in", "Sericulture / Silk Farmer", "Agriculture & Farming", "no", 12000, 120000,
      "Smallholder to silk-rearing business",
      "Rear silkworms and produce raw silk cocoons - a traditional agribusiness with govt support and steady textile demand.",
      S(("Silkworm Rearing","critical"),("Mulberry Cultivation","critical"),("Cocoon Handling","important"),
        ("Disease Management","important"),("Marketing","helpful")),
      ["Sericulture training (dept of sericulture/KVK)","Start rearing; sell cocoons to reelers","Scale and add reeling"],
      ["Sericulture training; no degree required"],
      ["sericulture","silk","agriculture","heritage"], ["Farm","Self-employed","Entrepreneurial"], "Stable - silk demand"),

    # ----- Finance / business (more) -----
    C("cost_accountant_in", "Cost & Management Accountant (CMA)", "Finance", "white", 30000, 250000,
      "Trainee to CFO-track / cost head",
      "Analyse and control costs, budgeting, and management accounting to drive business profitability and decisions.",
      S(("Cost Accounting","critical"),("Management Accounting","critical"),("Budgeting & Costing","important"),
        ("Financial Analysis","important"),("Compliance","helpful")),
      ["Clear ICMAI's CMA programme","Industry costing/finance roles","Rise to cost head/CFO track"],
      ["ICMAI CMA qualification"],
      ["cma","cost-accounting","finance","management"], ["Office","Knowledge work"], "Good"),
    C("credit_analyst_in", "Credit / Risk Analyst", "Finance", "white", 30000, 220000,
      "Analyst to risk manager",
      "Assess the creditworthiness of borrowers and manage financial risk for banks, NBFCs and lenders.",
      S(("Credit & Financial Analysis","critical"),("Risk Assessment","critical"),("Financial Statements","important"),
        ("Excel/Modelling","important"),("Regulatory Knowledge","helpful")),
      ["Finance degree/MBA/CA","Bank/NBFC credit roles","Grow to risk management"],
      ["MBA/CA/finance degree"],
      ["credit","risk","finance","banking"], ["Office","Knowledge work"], "Good"),
    C("business_dev_manager_in", "Business Development Manager", "Business & Management", "white", 30000, 250000,
      "Executive to BD/growth head",
      "Drive company growth - finding partnerships, new markets, clients and revenue opportunities, and closing deals.",
      S(("Business Development & Sales","critical"),("Relationship Building","critical"),("Market Analysis","important"),
        ("Negotiation","important"),("Strategy","helpful")),
      ["Sales/marketing/strategy background","BD/partnerships roles","Grow to BD/growth head"],
      ["Any degree; MBA helps; track record matters"],
      ["business-development","sales","growth","strategy"], ["Office / Field","Target-driven"], "Strong"),
    C("supply_chain_analyst_in", "Supply Chain / Logistics Analyst", "Supply Chain & Logistics", "white", 25000, 180000,
      "Analyst to supply-chain manager",
      "Optimise the flow of goods - planning, procurement, inventory, transport and demand - using data and systems.",
      S(("Supply Chain Planning","critical"),("Data Analysis & Excel","critical"),("Inventory/Demand Planning","important"),
        ("ERP Systems","important"),("Logistics Coordination","helpful")),
      ["Engineering/commerce/MBA-ops background","Analyst roles in mfg/retail/ecommerce","Grow to SC manager"],
      ["Any degree; MBA-Operations/SCM helps"],
      ["supply-chain","logistics","analytics","operations"], ["Office","Knowledge work"], "Strong - ecommerce & mfg"),

    # ----- Modern / digital / niche -----
    C("prompt_engineer_in", "AI / Prompt Engineer", "Technology", "white", 50000, 400000,
      "Practitioner to senior AI engineer",
      "Design prompts, tools and pipelines that get reliable results from LLMs - building AI features and agents for products.",
      S(("LLM/Prompt Engineering","critical"),("Programming (Python)","critical"),("APIs & Integration","important"),
        ("Evaluation & Testing","important"),("Domain Understanding","helpful")),
      ["Software/ML background + hands-on LLM work","Build AI features/agents; portfolio","AI engineering roles"],
      ["Any technical degree; demonstrable AI projects"],
      ["ai","llm","prompt-engineering","emerging-tech"], ["Office / Remote","High-skill"], "Growing fast - AI adoption"),
    C("mlops_engineer_in", "MLOps Engineer", "Technology", "white", 60000, 400000,
      "Engineer to senior/lead MLOps",
      "Deploy, scale and monitor machine-learning models in production - pipelines, infra and reliability for ML systems.",
      S(("ML Pipelines & Deployment","critical"),("Cloud & Containers (Docker/K8s)","critical"),("CI/CD for ML","important"),
        ("Monitoring","important"),("Python","important")),
      ["ML + DevOps/cloud skills","Move from ML/DevOps into MLOps","Own model deployment & reliability"],
      ["CS/IT degree or equivalent; cloud/ML experience"],
      ["mlops","ml","devops","cloud"], ["Office / Remote","High-skill"], "Strong"),
    C("sustainability_manager_in", "Sustainability / ESG Manager", "Business & Management", "white", 40000, 300000,
      "Analyst to ESG/sustainability head",
      "Help organisations measure and improve environmental, social and governance performance - reporting, compliance and strategy.",
      S(("ESG & Sustainability Frameworks","critical"),("Carbon/Impact Measurement","important"),("Reporting & Compliance","important"),
        ("Stakeholder Engagement","important"),("Data Analysis","helpful")),
      ["Environment/business background + ESG certification","Sustainability/CSR roles","Grow to ESG head"],
      ["Any degree; ESG/sustainability certification valued"],
      ["esg","sustainability","green-jobs","corporate"], ["Office","Knowledge work"], "Growing fast - ESG mandates"),
    C("affiliate_marketer_in", "Affiliate / Performance Marketer", "Marketing & Sales", "no", 15000, 300000,
      "Beginner to full-time performance marketer",
      "Drive online sales through content, ads and affiliate links, earning commissions or managing performance campaigns.",
      S(("Digital Marketing & Funnels","critical"),("SEO/Content or Paid Ads","critical"),("Analytics","important"),
        ("Audience Building","important"),("Copywriting","helpful")),
      ["Build a niche site/channel or learn paid ads","Affiliate programs / performance roles","Scale to agency or own brand"],
      ["No fixed degree; results and skill matter"],
      ["affiliate","marketing","digital","self-employment"], ["Online / Remote","Self-employed option"], "Growing - creator/affiliate economy"),
    C("ux_researcher_in", "UX Researcher", "Design & Creative", "white", 35000, 250000,
      "Researcher to lead UX researcher",
      "Study user behaviour and needs through interviews, testing and data to guide product and design decisions.",
      S(("User Research Methods","critical"),("Usability Testing","critical"),("Interviewing","important"),
        ("Data Synthesis","important"),("Communication","important")),
      ["Psychology/design/HCI background","Research/UX roles","Specialise and lead research"],
      ["Any degree; HCI/psychology/design helps; portfolio matters"],
      ["ux-research","design","product","research"], ["Office / Remote","Knowledge work"], "Good - product maturity"),
    C("data_governance_in", "Data Governance / Privacy Analyst", "Data & Analytics", "white", 35000, 250000,
      "Analyst to governance lead",
      "Ensure data is accurate, secure and compliant - policies, quality, privacy (DPDP/GDPR) and cataloguing across an organisation.",
      S(("Data Governance & Quality","critical"),("Privacy/Compliance (DPDP/GDPR)","critical"),("Data Cataloguing","important"),
        ("SQL/Data Basics","important"),("Stakeholder Management","helpful")),
      ["Data/IT/compliance background","Governance/privacy roles","Grow to data governance lead"],
      ["Any degree; data/privacy certifications valued"],
      ["data-governance","privacy","compliance","data"], ["Office / Remote","Knowledge work"], "Growing - data regulation"),
]


def main():
    with open(PATH, encoding="utf-8") as f:
        existing = json.load(f)
    ids = {c["id"] for c in existing}
    titles = {c["title"].strip().lower() for c in existing}
    to_add = []
    for c in NEW:
        if c["id"] in ids or c["title"].strip().lower() in titles:
            print("SKIP:", c["id"]); continue
        ids.add(c["id"]); titles.add(c["title"].strip().lower()); to_add.append(c)
    if not to_add:
        print("Nothing new."); return
    with open(PATH, encoding="utf-8") as f:
        text = f.read()
    idx = text.rstrip().rfind("]")
    head = text.rstrip()[:idx].rstrip()
    chunks = ["\n".join("  " + ln for ln in json.dumps(c, ensure_ascii=False, indent=2).splitlines()) for c in to_add]
    new_text = head + ",\n" + ",\n".join(chunks) + "\n]\n"
    parsed = json.loads(new_text)
    assert len(parsed) == len(existing) + len(to_add)
    with open(PATH, "w", encoding="utf-8") as f:
        f.write(new_text)
    print(f"Added {len(to_add)}. Total now {len(parsed)}.")


if __name__ == "__main__":
    main()
